import { CardIds } from '../card-ids';

export const duelsPassivePool1 = [
	CardIds.AllShallServeTavernBrawl,
	CardIds.AllTogetherNowTavernBrawl,
	CardIds.ArcaneFluxTavernBrawl,
	CardIds.ArcaniteCrystalTavernBrawl,
	CardIds.ArcticArmorTavernBrawl,
	CardIds.BitterColdTavernBrawl,
	CardIds.BookOfWonders,
	CardIds.CannibalismTavernBrawl,
	// CardIds.ConduitOfTheStormsTavernBrawl,
	CardIds.CrystalGemTavernBrawl,
	CardIds.DivineIlluminationTavernBrawl,
	CardIds.DragonbloodTavernBrawl,
	CardIds.DragonAffinityTavernBrawl,
	// CardIds.EverChangingElixirTavernBrawl,
	CardIds.FirekeepersIdolTavernBrawl,
	// CardIds.FireshaperTavernBrawl,
	CardIds.FreezeSolidTavernBrawl,
	CardIds.FromTheSwampTavernBrawl,
	CardIds.GrommashsArmguardsTavernBrawl,
	CardIds.HoldTheLineTavernBrawl,
	CardIds.InspiringPresenceTavernBrawl,
	CardIds.InvigoratingLightTavernBrawl,
	CardIds.KindlingFlameTavernBrawl,
	CardIds.LegendaryLootTavernBrawl,
	CardIds.MendingPoolsTavernBrawl,
	CardIds.MysteriousTomeTavernBrawl,
	CardIds.NaturalForceTavernBrawl,
	CardIds.OpenTheDoorwaysTavernBrawl,
	CardIds.PillageTheFallenTavernBrawl,
	CardIds.PlaguebringerTavernBrawl,
	CardIds.PotionOfSparkingTavernBrawl,
	CardIds.RecyclingTavernBrawl,
	// CardIds.RhoninsScryingOrbTavernBrawl,
	CardIds.RighteousReservesTavernBrawl,
	CardIds.RingOfPhaseshiftingTavernBrawl,
	CardIds.RobeOfTheApprenticeTavernBrawl,
	CardIds.RobesOfShrinkingTavernBrawl,
	CardIds.RocketBackpacksTavernBrawl,
	// CardIds.ScatteredCaltropsTavernBrawl,
	CardIds.Shadowcasting101TavernBrawl,
	CardIds.SmallBackpacksTavernBrawl,
	// CardIds.SmallPouchesTavernBrawl,
	CardIds.StaffOfPainTavernBrawl,
	CardIds.StakingAClaimTavernBrawl,
	CardIds.StarvingTavernBrawl,
	CardIds.StickyFingersTavernBrawl,
	CardIds.TheFloorIsLavaTavernBrawl,
	CardIds.UnholyGiftTavernBrawl,
	CardIds.UnlockedPotential,
	CardIds.WitherTheWeakTavernBrawl,
];

export const duelsPassivePool2 = [
	CardIds.AvengingArmamentsTavernBrawl,
	CardIds.BattleStanceTavernBrawl,
	CardIds.BattleTotem2,
	// CardIds.Caltrops,
	CardIds.BronzeSignetTavernBrawl,
	CardIds.CloakOfEmeraldDreamsTavernBrawl,
	CardIds.CorruptedFelstoneTavernBrawl,
	CardIds.DeathlyDeathTavernBrawl,
	CardIds.DisksOfLegend,
	CardIds.DoubleTime,
	CardIds.DraconicDreamTavernBrawl,
	CardIds.DragonboneRitualTavernBrawl,
	CardIds.EerieStoneTavernBrawl,
	CardIds.ElixirOfVigorTavernBrawl,
	CardIds.EmeraldGogglesTavernBrawl,
	CardIds.EnduranceTrainingTavernBrawl,
	CardIds.FlamesOfTheKirinTorTavernBrawl,
	CardIds.FlameWavesTavernBrawl,
	CardIds.GlacialDownpourTavernBrawl,
	CardIds.GreedyGainsTavernBrawl,
	CardIds.GuardianLightTavernBrawl,
	CardIds.HagathasEmbraceTavernBrawl,
	CardIds.HeavyArmorTavernBrawl,
	CardIds.IdolsOfEluneTavernBrawl,
	CardIds.ImpCredibleTrousersTavernBrawl,
	CardIds.IronRootsTavernBrawl,
	CardIds.KhadgarsScryingOrb,
	CardIds.MeekMasteryTavernBrawl,
	CardIds.MulchMadnessTavernBrawl,
	CardIds.MummyMagic,
	CardIds.OopsAllSpellsTavernBrawl,
	CardIds.OrbOfRevelationTavernBrawl,
	CardIds.PartyReplacementTavernBrawl,
	CardIds.RallyTheTroopsTavernBrawl,
	CardIds.RingOfBlackIceTavernBrawl,
	CardIds.RingOfRefreshmentTavernBrawl,
	CardIds.RunicHelmTavernBrawl,
	CardIds.ScepterOfSummoning,
	CardIds.SpecialDeliveryTavernBrawl,
	CardIds.SpreadingSaplingsTavernBrawl,
	CardIds.SunstridersCrownTavernBrawl,
	CardIds.TotemOfTheDead2,
	CardIds.UnstableMagicTavernBrawl,
];

export const duelsPassivePool2UltraRare = [
	CardIds.BandOfBeesTavernBrawl,
	CardIds.CapturedFlag,
	CardIds.ExpeditedBurialTavernBrawl,
	CardIds.ManastormTavernBrawl,
	CardIds.MantleOfIgnitionTavernBrawl,
	CardIds.RobeOfTheMagi,
	CardIds.Stargazing,
];

export const duelsActivePool1 = [
	CardIds.AmalgamateTavernBrawl,
	CardIds.AstralPortalTavernBrawl,
	CardIds.BeastlyBeautyTavernBrawl,
	CardIds.BubbaTavernBrawl,
	CardIds.ButchTavernBrawl,
	CardIds.BladeOfQueldelarTavernBrawl,
	CardIds.BloodMoonTavernBrawl,
	CardIds.ClockworkAssistantTavernBrawl,
	CardIds.CoinPouchTavernBrawl,
	CardIds.CreepyCurioTavernBrawl,
	CardIds.CrustyTheCrustaceanTavernBrawl,
	CardIds.Queldelar_HiltOfQueldelar,
	CardIds.Deathcharger,
	CardIds.Enrage,
	CardIds.GentlemansTopHat,
	CardIds.GoldenKobold,
	CardIds.GreedyPickaxeTavernBrawl,
	CardIds.HolyBookTavernBrawl,
	CardIds.HuntersInsightTavernBrawl,
	CardIds.JawsTavernBrawl,
	CardIds.LoyalHenchmanTavernBrawl,
	CardIds.LoyalSidekickTavernBrawl,
	CardIds.LoomingPresence,
	CardIds.MageArmorTavernBrawl,
	CardIds.MaskOfMimicryTavernBrawl,
	CardIds.MindpocalypseTavernBrawl,
	CardIds.MurlocHolmesTavernBrawl,
	CardIds.MutatingInjection,
	CardIds.NecroticPoisonTavernBrawl,
	CardIds.OldMilitiaHornTavernBrawl,
	CardIds.PartyPortalTavernBrawl2,
	CardIds.PrincessTavernBrawl,
	CardIds.PureColdTavernBrawl,
	CardIds.PuzzleBoxTavernBrawl,
	CardIds.RoyalGift,
	CardIds.SowTheSeedsTavernBrawl,
	CardIds.SpyglassTavernBrawl,
	CardIds.SuperchargeTavernBrawl,
	CardIds.SurlyMobTavernBrawl,
	CardIds.TheExorcisorTavernBrawl,
	CardIds.VampiricFangsToken,
	CardIds.WorshipperHeroic,
];

export const duelsActivePool2 = [
	CardIds.ArchmageStaffTavernBrawl,
	CardIds.BagOfCoinsTavernBrawl,
	CardIds.BookOfTheDeadTavernBrawl,
	CardIds.GrimmerPatron,
	CardIds.HyperblasterTavernBrawl,
	CardIds.AncientReflectionsTavernBrawl,
	CardIds.BagOfStuffingTavernBrawl,
	CardIds.Questionquestionquestion_BlackSoulstoneTavernBrawl,
	CardIds.BladeOfTheBurningSun,
	CardIds.GnomishArmyKnife,
	CardIds.BananaSplitTavernBrawl,
	CardIds.CanopicJarsTavernBrawl,
	CardIds.PhaorisBlade,
	CardIds.StaffOfScales,
	CardIds.WandOfDisintegrationTavernBrawl,
];

export const duelsActivePool2UltraRare = [
	CardIds.ChaosTheoryTavernBrawl,
	CardIds.OverpoweredTavernBrawl,
	CardIds.DreamgroveRing,
	CardIds.EmbersOfRagnarosTavernBrawl,
	CardIds.WaxRager,
	CardIds.WishTavernBrawl,
];

export const allDuelsTreasureCardIds = [
	...duelsPassivePool1,
	...duelsPassivePool2,
	...duelsPassivePool2UltraRare,
	...duelsActivePool1,
	...duelsActivePool2,
	...duelsActivePool2UltraRare,
];
