import { CardIds } from '../card-ids';

export const duelsPassivePool1 = [
	CardIds.AllShallServeTavernBrawl,
	CardIds.ArcaneFluxTavernBrawl,
	CardIds.ArcaniteCrystalTavernBrawl,
	CardIds.ArcticArmorTavernBrawl,
	CardIds.BitterColdTavernBrawl,
	CardIds.BookOfWonders,
	CardIds.CannibalismTavernBrawl,
	// CardIds.ConduitOfTheStormsTavernBrawl,
	CardIds.CrystalGemTavernBrawl,
	CardIds.DivineIlluminationTavernBrawl,
	CardIds.DragonbloodTavernBrawl,
	CardIds.DragonAffinityTavernBrawl,
	// CardIds.EverChangingElixirTavernBrawl,
	CardIds.FirekeepersIdolTavernBrawl,
	// CardIds.FireshaperTavernBrawl,
	CardIds.FreezeSolidTavernBrawl,
	CardIds.FromTheSwampTavernBrawl,
	CardIds.GrommashsArmguardsTavernBrawl,
	CardIds.HoldTheLineTavernBrawl,
	CardIds.InspiringPresenceTavernBrawl,
	CardIds.InvigoratingLightTavernBrawl,
	CardIds.KindlingFlameTavernBrawl,
	CardIds.LegendaryLootTavernBrawl,
	CardIds.MendingPoolsTavernBrawl,
	CardIds.MysteriousTomeTavernBrawl,
	CardIds.NaturalForceTavernBrawl,
	CardIds.OpenTheDoorwaysTavernBrawl,
	CardIds.PillageTheFallenTavernBrawl,
	CardIds.PlaguebringerTavernBrawl,
	CardIds.PotionOfSparkingTavernBrawl,
	CardIds.RecyclingTavernBrawl,
	// CardIds.RhoninsScryingOrbTavernBrawl,
	CardIds.RighteousReservesTavernBrawl,
	CardIds.RingOfPhaseshiftingTavernBrawl,
	CardIds.RobeOfTheApprenticeTavernBrawl,
	CardIds.RobesOfShrinkingTavernBrawl,
	CardIds.RocketBackpacksTavernBrawl,
	// CardIds.ScatteredCaltropsTavernBrawl,
	CardIds.SmallBackpacksTavernBrawl,
	// CardIds.SmallPouchesTavernBrawl,
	CardIds.StaffOfPainTavernBrawl,
	CardIds.StakingAClaimTavernBrawl,
	CardIds.StarvingTavernBrawl,
	CardIds.StickyFingersTavernBrawl,
	CardIds.TheFloorIsLavaTavernBrawl,
	CardIds.UnholyGiftTavernBrawl,
	CardIds.UnlockedPotential,
	CardIds.WitherTheWeakTavernBrawl,
];

export const duelsPassivePool2 = [
	CardIds.AllTogetherNowTavernBrawl,
	CardIds.AvengingArmamentsTavernBrawl,
	CardIds.BattleStanceTavernBrawl,
	// CardIds.Caltrops,
	CardIds.BronzeSignetTavernBrawl,
	CardIds.CloakOfEmeraldDreamsTavernBrawl,
	CardIds.CorruptedFelstoneTavernBrawl,
	CardIds.DeathlyDeathTavernBrawl,
	CardIds.DoubleTime,
	CardIds.DraconicDreamTavernBrawl,
	CardIds.DragonboneRitualTavernBrawl,
	CardIds.EerieStoneTavernBrawl,
	CardIds.ElixirOfVigorTavernBrawl,
	CardIds.EmeraldGogglesTavernBrawl,
	CardIds.EnduranceTrainingTavernBrawl,
	CardIds.FlamesOfTheKirinTorTavernBrawl,
	CardIds.FlameWavesTavernBrawl,
	CardIds.GlacialDownpourTavernBrawl,
	CardIds.GreedyGainsTavernBrawl,
	CardIds.GuardianLightTavernBrawl,
	CardIds.HagathasEmbraceTavernBrawl,
	CardIds.HeavyArmorTavernBrawl,
	CardIds.IdolsOfEluneTavernBrawl,
	CardIds.ImpCredibleTrousersTavernBrawl,
	CardIds.IronRootsTavernBrawl,
	CardIds.KhadgarsScryingOrb,
	CardIds.MeekMasteryTavernBrawl,
	CardIds.MulchMadnessTavernBrawl,
	CardIds.MummyMagic,
	CardIds.OopsAllSpellsTavernBrawl,
	CardIds.OrbOfRevelationTavernBrawl,
	CardIds.PartyReplacementTavernBrawl,
	CardIds.RallyTheTroopsTavernBrawl,
	CardIds.RingOfBlackIceTavernBrawl,
	CardIds.RingOfRefreshmentTavernBrawl,
	CardIds.RunicHelmTavernBrawl,
	CardIds.ScepterOfSummoning,
	CardIds.SpecialDeliveryTavernBrawl,
	CardIds.SpreadingSaplingsTavernBrawl,
	CardIds.SunstridersCrownTavernBrawl,
	CardIds.UnstableMagicTavernBrawl,
];

export const duelsPassivePool2UltraRare = [
	CardIds.BandOfBeesTavernBrawl,
	CardIds.BattleTotem2,
	CardIds.CapturedFlag,
	CardIds.DisksOfLegend,
	CardIds.ExpeditedBurialTavernBrawl,
	CardIds.ManastormTavernBrawl,
	CardIds.MantleOfIgnitionTavernBrawl,
	CardIds.RobeOfTheMagi,
	CardIds.Shadowcasting101TavernBrawl,
	CardIds.Stargazing,
	CardIds.TotemOfTheDead2,
];

export const duelsActivePool1 = [
	CardIds.AmalgamateTavernBrawl,
	CardIds.AstralPortalTavernBrawl,
	CardIds.BeastlyBeautyTavernBrawl,
	CardIds.BubbaTavernBrawl,
	CardIds.ButchTavernBrawl,
	CardIds.BladeOfQueldelarTavernBrawl,
	CardIds.BloodMoonTavernBrawl,
	CardIds.ClockworkAssistantTavernBrawl,
	CardIds.CoinPouchTavernBrawl,
	CardIds.CreepyCurioTavernBrawl,
	CardIds.CrustyTheCrustaceanTavernBrawl,
	CardIds.Queldelar_HiltOfQueldelar,
	CardIds.Deathcharger,
	CardIds.Enrage,
	CardIds.GentlemansTopHat,
	CardIds.GoldenKobold,
	CardIds.GreedyPickaxeTavernBrawl,
	CardIds.HolyBookTavernBrawl,
	CardIds.HuntersInsightTavernBrawl,
	CardIds.JawsTavernBrawl,
	CardIds.LoyalHenchmanTavernBrawl,
	CardIds.LoyalSidekickTavernBrawl,
	CardIds.LoomingPresence,
	CardIds.MageArmorTavernBrawl,
	CardIds.MaskOfMimicryTavernBrawl,
	CardIds.MindpocalypseTavernBrawl,
	CardIds.MurlocHolmesTavernBrawl,
	CardIds.MutatingInjection,
	CardIds.NecroticPoisonTavernBrawl,
	CardIds.OldMilitiaHornTavernBrawl,
	CardIds.PartyPortalTavernBrawl2,
	CardIds.PrincessTavernBrawl,
	CardIds.PureColdTavernBrawl,
	CardIds.PuzzleBoxTavernBrawl,
	CardIds.RoyalGift,
	CardIds.SowTheSeedsTavernBrawl,
	CardIds.SpyglassTavernBrawl,
	CardIds.SuperchargeTavernBrawl,
	CardIds.SurlyMobTavernBrawl,
	CardIds.TheExorcisorTavernBrawl,
	CardIds.VampiricFangsToken,
	CardIds.WorshipperHeroic,
];

export const duelsActivePool2 = [
	CardIds.ArchmageStaffTavernBrawl,
	CardIds.BagOfCoinsTavernBrawl,
	CardIds.BookOfTheDeadTavernBrawl,
	CardIds.GrimmerPatron,
	CardIds.HyperblasterTavernBrawl,
	CardIds.AncientReflectionsTavernBrawl,
	CardIds.BagOfStuffingTavernBrawl,
	CardIds.Questionquestionquestion_BlackSoulstoneTavernBrawl,
	CardIds.BladeOfTheBurningSun,
	CardIds.GnomishArmyKnife,
	CardIds.BananaSplitTavernBrawl,
	CardIds.CanopicJarsTavernBrawl,
	CardIds.PhaorisBlade,
	CardIds.StaffOfScales,
	CardIds.WandOfDisintegrationTavernBrawl,
];

export const duelsActivePool2UltraRare = [
	CardIds.ChaosTheoryTavernBrawl,
	CardIds.OverpoweredTavernBrawl,
	CardIds.DreamgroveRing,
	CardIds.EmbersOfRagnarosTavernBrawl,
	CardIds.WaxRager,
	CardIds.WishTavernBrawl,
];

export const allDuelsTreasureCardIds = [
	...duelsPassivePool1,
	...duelsPassivePool2,
	...duelsPassivePool2UltraRare,
	...duelsActivePool1,
	...duelsActivePool2,
	...duelsActivePool2UltraRare,
];

export const allDuelsHeroes = [
	CardIds.MindrenderIlluciaTavernBrawl,
	CardIds.RattlegoreTavernBrawl,
	CardIds.TuralyonTheTenuredTavernBrawl,
	CardIds.StarStudentStelinaTavernBrawl,
	CardIds.ProfessorSlateTavernBrawl,
	CardIds.ForestWardenOmuTavernBrawl,
	CardIds.MozakiMasterDuelistTavernBrawl,
	CardIds.ArchwitchWillowTavernBrawl,
	CardIds.InstructorFireheartTavernBrawlToken,
	CardIds.InfiltratorLilianTavernBrawl,
	CardIds.VanndarStormpikeTavernBrawl,
	CardIds.DrektharTavernBrawl,
];

export const normalizeDuelsHeroCardId = (heroCardId: string): string => {
	switch (heroCardId) {
		case CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl1:
		case CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl2:
		case CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl3:
		case CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl4:
		case CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl5:
			return CardIds.VanndarStormpikeTavernBrawl;
		case CardIds.Drekthar_DrektharTavernBrawl1:
		case CardIds.Drekthar_DrektharTavernBrawl2:
		case CardIds.Drekthar_DrektharTavernBrawl3:
		case CardIds.Drekthar_DrektharTavernBrawl4:
		case CardIds.Drekthar_DrektharTavernBrawl5:
			return CardIds.DrektharTavernBrawl;
		default:
			return heroCardId;
	}
};

export const allDuelsSignatureTreasures = [
	CardIds.BladeOfQuickeningTavernBrawlToken,
	CardIds.BindingChainsTavernBrawlToken,
	CardIds.GiftOfTheLegionTavernBrawl,
	CardIds.MoargOutcastTavernBrawlToken,
	CardIds.SummoningRitualTavernBrawlToken,
	CardIds.AwakenedAncientTavernBrawl,
	CardIds.HerdingHornTavernBrawlToken,
	CardIds.MarvelousMyceliumTavernBrawlToken,
	CardIds.MoonbeastTavernBrawlToken,
	CardIds.WardensInsightTavernBrawlToken,
	CardIds.ZukaraTheWildTavernBrawl,
	CardIds.BonecrusherTavernBrawlToken,
	CardIds.CarrotOnAStickTavernBrawl,
	CardIds.DeathstriderTavernBrawl,
	CardIds.SlatesSyringeTavernBrawl,
	CardIds.StalkingPrideTavernBrawlToken,
	CardIds.TraktamerAelessaTavernBrawl,
	CardIds.BritzBlazebucketTavernBrawl,
	CardIds.ElementalLearningTavernBrawl,
	CardIds.EmbercasterTavernBrawl,
	CardIds.InfiniteArcaneTavernBrawlToken,
	CardIds.WandOfDuelingTavernBrawlToken,
	CardIds.YoggTasticTastiesTavernBrawl,
	CardIds.DrocomurchanicasTavernBrawlToken,
	CardIds.FavoredRacerTavernBrawl,
	CardIds.HumbleBlessingsTavernBrawl,
	CardIds.MenAtArmsTavernBrawlToken,
	CardIds.RoyalGreatswordTavernBrawlToken,
	CardIds.SuLeadfootTavernBrawl,
	CardIds.DropletOfInsanityTavernBrawlToken,
	CardIds.FracturedSpiritsTavernBrawlToken,
	CardIds.HeraldOfTheScaledOnesTavernBrawl,
	CardIds.JorasThuldoomTavernBrawl,
	CardIds.ScionOfTheDeepTavernBrawlToken,
	CardIds.ShadowWordVoidTavernBrawl,
	CardIds.AceInTheHoleTavernBrawlToken,
	CardIds.AcquiredAlliesTavernBrawlToken,
	CardIds.DeadlyWeapons101TavernBrawlToken,
	CardIds.GreenTortollanShellTavernBrawl,
	CardIds.NerubianPeddlerTavernBrawlToken,
	CardIds.ChaosStormTavernBrawl,
	CardIds.FluctuatingTotemTavernBrawlToken,
	CardIds.InvokeTheVoidTavernBrawlToken,
	CardIds.PayloadTotemSpecialistTavernBrawl,
	CardIds.TempestsFuryTavernBrawlToken,
	CardIds.Demonology101TavernBrawlToken,
	CardIds.DemonizerTavernBrawlToken,
	CardIds.GiftOfTheOldGodsTavernBrawlToken,
	CardIds.ImpishAidTavernBrawl,
	CardIds.KillmoxTheBanishedOneTavernBrawlToken,
	CardIds.AutoArmamentsTavernBrawlToken,
	CardIds.BrewsterTheBrutalTavernBrawlToken,
	CardIds.CollectorsIreTavernBrawlToken,
	CardIds.ScrapmetalDemolitionistTavernBrawl,
	CardIds.SpikedArmsTavernBrawlToken,

	CardIds.ApocalypseTavernBrawlToken,
	CardIds.ClawsOfTerrorTavernBrawlToken,
	CardIds.FireStompTavernBrawlToken,
	CardIds.HornsOfFlameTavernBrawlToken,
	CardIds.SoulstoneTrapTavernBrawlToken,
	CardIds.Questionquestionquestion_BlackSoulstoneTavernBrawl,

	CardIds.ValorousDisplayTavernBrawlToken,
	CardIds.ElementalChaosTavernBrawlToken,
	CardIds.PactOfTheLichTavernBrawlToken,
	CardIds.MagisterUnchainedTavernBrawlToken,
	CardIds.GiftOfTheHeartTavernBrawlToken,
	CardIds.ForTheHordeTavernBrawlToken,
	CardIds.ForgeInLightTavernBrawlToken,
	CardIds.SpymastersGambitTavernBrawlToken,
	CardIds.StalkersSuppliesTavernBrawlToken,
	CardIds.RendingAmbushTavernBrawlToken,
	CardIds.DevoutBlessingsTavernBrawlToken,
	CardIds.ForTheAllianceTavernBrawlToken,
];

// Maybe it's possible to extract this from the game files or memory somehow?
// Since it doesn't change often it's ok to maintain it manually, at least for now
export const duelsHeroConfigs = [
	{
		hero: CardIds.StarStudentStelinaTavernBrawl,
		heroPowers: [
			CardIds.InfernalStrikeTavernBrawl,
			CardIds.OutlanderTavernBrawl,
			CardIds.IllidariStrikeTavernBrawl,
		],
		signatureTreasures: [
			CardIds.SummoningRitualTavernBrawlToken,
			CardIds.MoargOutcastTavernBrawlToken,
			CardIds.GiftOfTheLegionTavernBrawl,
			CardIds.BindingChainsTavernBrawlToken,
			CardIds.BladeOfQuickeningTavernBrawlToken,
			CardIds.TraktamerAelessaTavernBrawl,
		],
	},
	{
		hero: CardIds.ForestWardenOmuTavernBrawl,
		heroPowers: [
			CardIds.NaturesGiftsTavernBrawl,
			CardIds.InvigoratingBloomTavernBrawl,
			CardIds.HarvestTimeTavernBrawl,
		],
		signatureTreasures: [
			CardIds.WardensInsightTavernBrawlToken,
			CardIds.MoonbeastTavernBrawlToken,
			CardIds.HerdingHornTavernBrawlToken,
			CardIds.MarvelousMyceliumTavernBrawlToken,
			CardIds.AwakenedAncientTavernBrawl,
			CardIds.ZukaraTheWildTavernBrawl,
		],
	},
	{
		hero: CardIds.ProfessorSlateTavernBrawl,
		heroPowers: [
			CardIds.SurvivalTrainingTavernBrawl,
			CardIds.DeathGamesTavernBrawl,
			CardIds.SavageSecretsTavernBrawl,
		],
		signatureTreasures: [
			CardIds.SlatesSyringeTavernBrawl,
			CardIds.BonecrusherTavernBrawlToken,
			CardIds.StalkingPrideTavernBrawlToken,
			CardIds.DeathstriderTavernBrawl,
			CardIds.CarrotOnAStickTavernBrawl,
			CardIds.TraktamerAelessaTavernBrawl,
		],
	},
	{
		hero: CardIds.MozakiMasterDuelistTavernBrawl,
		heroPowers: [CardIds.WyrmBoltTavernBrawl, CardIds.SecretStudiesTavernBrawl, CardIds.FrostShardsTavernBrawl],
		signatureTreasures: [
			CardIds.WandOfDuelingTavernBrawlToken,
			CardIds.ElementalLearningTavernBrawl,
			CardIds.InfiniteArcaneTavernBrawlToken,
			CardIds.EmbercasterTavernBrawl,
			CardIds.YoggTasticTastiesTavernBrawl,
			CardIds.BritzBlazebucketTavernBrawl,
		],
	},
	{
		hero: CardIds.TuralyonTheTenuredTavernBrawl,
		heroPowers: [
			CardIds.FromGoldenLightTavernBrawl,
			CardIds.BringOnRecruitsTavernBrawl,
			CardIds.ModestAspirationsTavernBrawl,
		],
		signatureTreasures: [
			CardIds.RoyalGreatswordTavernBrawlToken,
			CardIds.MenAtArmsTavernBrawlToken,
			CardIds.DrocomurchanicasTavernBrawlToken,
			CardIds.FavoredRacerTavernBrawl,
			CardIds.HumbleBlessingsTavernBrawl,
			CardIds.SuLeadfootTavernBrawl,
		],
	},
	{
		hero: CardIds.MindrenderIlluciaTavernBrawl,
		heroPowers: [CardIds.ShadowMendTavernBrawl, CardIds.MindTetherTavernBrawl, CardIds.CallOfMadnessTavernBrawl],
		signatureTreasures: [
			CardIds.FracturedSpiritsTavernBrawlToken,
			CardIds.DropletOfInsanityTavernBrawlToken,
			CardIds.ScionOfTheDeepTavernBrawlToken,
			CardIds.ShadowWordVoidTavernBrawl,
			CardIds.HeraldOfTheScaledOnesTavernBrawl,
			CardIds.JorasThuldoomTavernBrawl,
		],
	},
	{
		hero: CardIds.InfiltratorLilianTavernBrawl,
		heroPowers: [
			CardIds.RoguishManeuversTavernBrawl,
			CardIds.ConnectionsTavernBrawl,
			CardIds.VileConcoctionTavernBrawl,
		],
		signatureTreasures: [
			CardIds.DeadlyWeapons101TavernBrawlToken,
			CardIds.NerubianPeddlerTavernBrawlToken,
			CardIds.AcquiredAlliesTavernBrawlToken,
			CardIds.AceInTheHoleTavernBrawlToken,
			CardIds.GreenTortollanShellTavernBrawl,
			CardIds.BritzBlazebucketTavernBrawl,
		],
	},
	{
		hero: CardIds.ArchwitchWillowTavernBrawl,
		heroPowers: [CardIds.DarkArtsTavernBrawl, CardIds.DemonBloodTavernBrawl, CardIds.SoulcialStudiesTavernBrawl],
		signatureTreasures: [
			CardIds.ImpishAidTavernBrawl,
			CardIds.GiftOfTheOldGodsTavernBrawlToken,
			CardIds.KillmoxTheBanishedOneTavernBrawlToken,
			CardIds.DemonizerTavernBrawlToken,
			CardIds.Demonology101TavernBrawlToken,
			CardIds.JorasThuldoomTavernBrawl,
		],
	},
	{
		hero: CardIds.DiabloTavernBrawl,
		heroPowers: [
			CardIds.DoomChargeTavernBrawl,
			CardIds.PrimalPowerTavernBrawl,
			CardIds.DemonicTransformationTavernBrawl,
		],
		signatureTreasures: [
			CardIds.ClawsOfTerrorTavernBrawlToken,
			CardIds.FireStompTavernBrawlToken,
			CardIds.ApocalypseTavernBrawlToken,
			CardIds.SoulstoneTrapTavernBrawlToken,
			CardIds.HornsOfFlameTavernBrawlToken,
			CardIds.QuestionquestionquestionTavernBrawlToken,
		],
	},
	{
		hero: CardIds.RattlegoreTavernBrawl,
		heroPowers: [CardIds.NoGutsNoGloryTavernBrawl, CardIds.BruisingTavernBrawl, CardIds.MagneticMinesTavernBrawl],
		signatureTreasures: [
			CardIds.AutoArmamentsTavernBrawlToken,
			CardIds.CollectorsIreTavernBrawlToken,
			CardIds.BrewsterTheBrutalTavernBrawlToken,
			CardIds.ScrapmetalDemolitionistTavernBrawl,
			CardIds.SpikedArmsTavernBrawlToken,
			CardIds.SuLeadfootTavernBrawl,
		],
	},
	{
		hero: CardIds.DrektharTavernBrawl,
		alternateHeroes: [
			CardIds.Drekthar_DrektharTavernBrawl1,
			CardIds.Drekthar_DrektharTavernBrawl2,
			CardIds.Drekthar_DrektharTavernBrawl3,
			CardIds.Drekthar_DrektharTavernBrawl4,
			CardIds.Drekthar_DrektharTavernBrawl5,
		],
		heroPowers: [
			CardIds.WarmastersFrenzyTavernBrawl,
			CardIds.HarnessTheElementsTavernBrawl,
			CardIds.WarCommandsTavernBrawl,
		],
		signatureTreasures: [
			CardIds.ValorousDisplayTavernBrawlToken,
			CardIds.ElementalChaosTavernBrawlToken,
			CardIds.PactOfTheLichTavernBrawlToken,
			CardIds.MagisterUnchainedTavernBrawlToken,
			CardIds.GiftOfTheHeartTavernBrawlToken,
			CardIds.ForTheHordeTavernBrawlToken,
		],
	},
	{
		hero: CardIds.VanndarStormpikeTavernBrawl,
		alternateHeroes: [
			CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl1,
			CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl2,
			CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl3,
			CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl4,
			CardIds.VanndarStormpike_VanndarStormpikeTavernBrawl5,
		],
		heroPowers: [CardIds.PromoteTavernBrawl, CardIds.SendInTheScoutTavernBrawl, CardIds.BattleTacticsTavernBrawl],
		signatureTreasures: [
			CardIds.ForgeInLightTavernBrawlToken,
			CardIds.SpymastersGambitTavernBrawlToken,
			CardIds.StalkersSuppliesTavernBrawlToken,
			CardIds.RendingAmbushTavernBrawlToken,
			CardIds.DevoutBlessingsTavernBrawlToken,
			CardIds.ForTheAllianceTavernBrawlToken,
		],
	},
];
