import { CardIds } from '../../card-ids';

/** JAIL / Underbelly expansion — static related card links. */
export const JAIL_RELATED_CARDS = {
	[CardIds.VigilantSentry_JAIL_035]: [CardIds.VigilantSentry_JAIL_035],
	[CardIds.SecretIngredient_JAIL_201]: [CardIds.ALittleofThis_JAIL_201a, CardIds.ADashofThat_JAIL_201b],
	[CardIds.ContrabandWands_JAIL_312]: [CardIds.ArcaneMissilesLegacy],
	[CardIds.ScarletBruiser_JAIL_328]: [CardIds.ScarletBruiser_JAIL_328],
	[CardIds.ScrambleforGear_JAIL_386]: [CardIds.FoundGear_JAIL_386t],
	[CardIds.ImpGangStooge_JAIL_399]: [CardIds.GrandmotherImp_JAIL_399t1],
	[CardIds.WidowsBite_JAIL_436]: [CardIds.WidowsFeast_JAIL_436t],
	[CardIds.WidowsFeast_JAIL_436t]: [CardIds.WidowsBanquet_JAIL_436t2],
	[CardIds.DisguisedDoctor_JAIL_442]: [CardIds.Blight_JAIL_443t],
	[CardIds.TheLivingPlague_JAIL_443]: [CardIds.Blight_JAIL_443t],
	[CardIds.BloodDoctorThalena_JAIL_446]: [CardIds.VampyrsKiss_JAIL_446hp],
	[CardIds.RecklessDetective_JAIL_447]: [CardIds.DetectivesClothes_JAIL_447t],
	[CardIds.EmergencySurgery_JAIL_454]: [CardIds.Necronurse_JAIL_454t],
	[CardIds.TinyPal_JAIL_458]: [
		CardIds.TinyPal_JAIL_458t1,
		CardIds.TinyPal_JAIL_458t2,
		CardIds.TinyPal_JAIL_458t3,
		CardIds.TinyPal_JAIL_458t4,
	],
	[CardIds.TinyPal_JAIL_458t1]: [CardIds.TinyPal_JAIL_458t2, CardIds.TinyPal_JAIL_458t3, CardIds.TinyPal_JAIL_458t4],
	[CardIds.TinyPal_JAIL_458t2]: [CardIds.TinyPal_JAIL_458t1, CardIds.TinyPal_JAIL_458t3, CardIds.TinyPal_JAIL_458t4],
	[CardIds.TinyPal_JAIL_458t3]: [CardIds.TinyPal_JAIL_458t1, CardIds.TinyPal_JAIL_458t2, CardIds.TinyPal_JAIL_458t4],
	[CardIds.TinyPal_JAIL_458t4]: [CardIds.TinyPal_JAIL_458t1, CardIds.TinyPal_JAIL_458t2, CardIds.TinyPal_JAIL_458t3],
	[CardIds.AyaLotusKingpin_JAIL_504]: [
		CardIds.JadeCoin_JAIL_504t,
		CardIds.GrimyCoin_JAIL_504t2,
		CardIds.KabalCoin_JAIL_504t3,
	],
	[CardIds.JadeCoin_JAIL_504t]: [
		CardIds.JadeGolem_JAIL_504tt01,
		CardIds.JadeGolem_JAIL_504tt04,
		CardIds.JadeGolem_JAIL_504tt07,
		CardIds.JadeGolem_JAIL_504tt20,
	],
	[CardIds.SpireofSolitude_JAIL_511]: [CardIds.ShivarraInfiltrator_JAIL_511t],
	[CardIds.LotusBookie_JAIL_720]: [CardIds.TheCoinCore],
	[CardIds.StardustScythe_JAIL_730]: [CardIds.VoidSoul_JAIL_732],
	[CardIds.ViciousVoidscale_JAIL_733]: [CardIds.VoidSoul_JAIL_732],
	[CardIds.MugZee_JAIL_800]: [CardIds.MugsMagic_JAIL_800hp1, CardIds.ZeesMight_JAIL_800hp2],
	[CardIds.MoltenGold_JAIL_801]: [CardIds.MoltenGoldElemental_JAIL_801t],
	[CardIds.Frostshatter_JAIL_803]: [CardIds.FrostshatterElemental_JAIL_803t],
	[CardIds.Stormfury_JAIL_805]: [CardIds.StormfuryElemental_JAIL_805t],
	[CardIds.UnderbellyNetwork_JAIL_877]: [CardIds.SnootHoarder_JAIL_877t],
	[CardIds.BeastTripwire_JAIL_879]: [CardIds.TrippedBeastTripwire_JAIL_879t],
	[CardIds.ArcaneTripwire_JAIL_881]: [CardIds.TrippedArcaneTripwire_JAIL_881t],
	[CardIds.ZuramatsPrison_JAIL_887]: [CardIds.ZuramattheObliterator_JAIL_887t2, CardIds.WhisperoftheVoid_JAIL_887t3],
	[CardIds.VoidBlast_JAIL_891]: [CardIds.VoidSoul_JAIL_732],
	[CardIds.Moragg_JAIL_906]: [CardIds.Moragg_JAIL_906],
	[CardIds.HolyEmbrace_JAIL_941]: [CardIds.DarkEmbrace_JAIL_941t],
	[CardIds.CapturedArchmage_JAIL_974]: [CardIds.FireballLegacy],
};
