import { CardIds } from 'src/card-ids';
import { ReferenceCard } from 'src/public-api';

const ADVENTURER_TOKENS = [
	CardIds.PartyUp_BurlyAdventurerToken,
	CardIds.PartyUp_ArcaneAdventurerToken,
	CardIds.PartyUp_DeadlyAdventurerToken,
	CardIds.PartyUp_DevoutAdventurerToken,
	CardIds.PartyUp_RelentlessAdventurerToken,
	CardIds.PartyUp_SneakyAdventurerToken,
	CardIds.PartyUp_SwiftAdventurerToken,
	CardIds.PartyUp_VitalAdventurerToken,
];
const ANIMAL_COMPANION_TOKENS = [CardIds.HufferLegacy, CardIds.LeokkLegacy, CardIds.MishaLegacy];
const DREAM_CARDS = [
	CardIds.DreamLegacy,
	CardIds.EmeraldDrakeLegacy,
	CardIds.LaughingSisterLegacy,
	CardIds.NightmareLegacy,
	CardIds.YseraAwakensLegacy,
];
const LACKEY_TOKENS = [
	CardIds.DraconicLackey,
	CardIds.EtherealLackey,
	CardIds.FacelessLackey,
	CardIds.GoblinLackey,
	CardIds.KoboldLackey,
	CardIds.TitanicLackey,
	CardIds.WitchyLackey,
];
const PIRANHA_TOKENS = [
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken1,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken2,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken3,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken4,
];

export type RelatedCardExtractor = (cards: readonly ReferenceCard[]) => readonly string[];

export const RELATED_CARDS_DATA: {
	[cardId: string]: readonly (string | RelatedCardExtractor)[];
} = {
	[CardIds.AbyssalWave]: [CardIds.SirakessCultist_AbyssalCurseToken],
	[CardIds.AdorableInfestation]: [CardIds.AdorableInfestation_MarsuulCubToken],
	// [CardIds.ApothecaryHelbrim]: [
	// 	CardIds.DeadlyPoisonCore,
	// 	CardIds.LeechingPoison,
	// 	CardIds.NitroboostPoison,
	// 	CardIds.ParalyticPoison,
	// 	CardIds.SilverleafPoison,
	// ], // Generation depends on the game mode you're playing (incl Arena / Duels probably)
	[CardIds.ArborUp]: [CardIds.FaireArborist_TreantToken],
	[CardIds.ArcaneOverflow]: [CardIds.ArcaneOverflow_ArcaneRemnantToken],
	[CardIds.ArchdruidNaralex]: DREAM_CARDS,
	[CardIds.AuspiciousSpirits]: [CardIds.AuspiciousSpirits_AuspiciousSpirits],
	[CardIds.AzsharanDefector]: [CardIds.AzsharanDefector_SunkenDefectorToken],
	[CardIds.AzsharanGardens]: [CardIds.AzsharanGardens_SunkenGardensToken],
	[CardIds.AzsharanMooncatcher]: [CardIds.AzsharanMooncatcher_SunkenMooncatcherToken],
	[CardIds.AzsharanRitual]: [CardIds.AzsharanRitual_SunkenRitualToken],
	[CardIds.AzsharanSaber]: [CardIds.AzsharanSaber_SunkenSaberToken],
	[CardIds.AzsharanScavenger]: [CardIds.AzsharanScavenger_SunkenScavengerToken],
	[CardIds.AzsharanScroll]: [CardIds.AzsharanScroll_SunkenScrollToken],
	[CardIds.AzsharanSentinel]: [CardIds.AzsharanSentinel_SunkenSentinelToken],
	[CardIds.AzsharanSweeper]: [CardIds.AzsharanSweeper_SunkenSweeperToken],
	[CardIds.AzsharanTrident]: [CardIds.AzsharanTrident_SunkenTridentToken],
	[CardIds.AzsharanVessel]: [
		CardIds.AzsharanVessel_SunkenVesselToken,
		CardIds.AzsharanVessel_AzsharanPirateToken,
		CardIds.AzsharanVessel_SunkenPirateToken,
	],
	[CardIds.BananaVendor]: [CardIds.BananaVendor_BananasToken],
	[CardIds.Barricade]: [CardIds.Barricade_RaceGuardToken],
	[CardIds.BattlewornVanguard]: [CardIds.Umberwing_FelwingToken],
	[CardIds.BearonGlashear]: [CardIds.BearonGlashear_FrozenStagguardToken],
	[CardIds.BeaststalkerTavish]: [
		CardIds.BeaststalkerTavish_ImprovedExplosiveTrapToken,
		CardIds.BeaststalkerTavish_ImprovedFreezingTrapToken,
		CardIds.BeaststalkerTavish_ImprovedIceTrapToken,
		CardIds.BeaststalkerTavish_ImprovedOpenTheCagesToken,
		CardIds.BeaststalkerTavish_ImprovedPackTacticsToken,
		CardIds.BeaststalkerTavish_ImprovedSnakeTrapToken,
		CardIds.BeaststalkerTavish_SummonPet,
	],
	[CardIds.BestInShell]: [CardIds.BestInShell_GoldshellTurtleToken],
	[CardIds.BlackscaleBrute]: [CardIds.BlackscaleBrute_FirescaleBerserkerToken],
	[CardIds.BlackwaterBehemoth]: [CardIds.BlackwaterBehemoth_BehemothsLureToken],
	[CardIds.BloodInTheWater]: [CardIds.BloodInTheWater_TigerSharkToken],
	[CardIds.BonewebEgg]: [CardIds.BonewebEgg_BonewebSpiderToken],
	[CardIds.BuildASnowman]: [
		CardIds.BuildASnowman_BuildASnowbruteToken,
		CardIds.BuildASnowman_BuildASnowgreToken,
		CardIds.BuildASnowman_SnowbruteToken,
		CardIds.BuildASnowman_SnowgreToken,
		CardIds.BuildASnowman_SnowmanToken,
	],
	[CardIds.BumperCar]: [CardIds.BumperCar_DarkmoonRiderToken],
	[CardIds.BurningBladeAcolyte]: [CardIds.BurningBladeAcolyte_DemonspawnToken],
	[CardIds.BrukanOfTheElements]: [
		CardIds.BrukanOfTheElements_ElementalMastery,
		CardIds.ElementalMastery_EarthInvocationToken,
		CardIds.ElementalMastery_FireInvocationToken,
		CardIds.ElementalMastery_LightningInvocationToken,
		CardIds.ElementalMastery_CommandTheElementsToken,
		CardIds.BrukanOfTheElements_EarthInvocationToken,
		CardIds.BrukanOfTheElements_WaterInvocation,
		CardIds.BrukanOfTheElements_WaterInvocationToken,
		CardIds.BrukanOfTheElements_FireInvocationToken,
		CardIds.BrukanOfTheElements_LightningInvocationToken,
		CardIds.BrukanOfTheElements_EarthenGuardianToken,
	],
	[CardIds.CannonmasterSmythe1]: [CardIds.CannonmasterSmythe_NorthwatchSoldierToken],
	[CardIds.CarouselGryphon]: [CardIds.CarouselGryphon_CarouselGryphonToken],
	[CardIds.CarnivalClown]: [CardIds.CarnivalClown_CarnivalClownToken],
	[CardIds.CascadingDisaster]: [
		CardIds.CascadingDisaster_CascadingDisasterToken1,
		CardIds.CascadingDisaster_CascadingDisasterToken2,
	],
	[CardIds.ChainLightningRank1]: [
		CardIds.ChainLightningRank1_ChainLightningRank2Token,
		CardIds.ChainLightningRank1_ChainLightningRank3Token,
	],
	[CardIds.CircusMedic]: [CardIds.CircusMedic_CircusMedicToken],
	[CardIds.CityArchitect]: [CardIds.CityArchitect_CastleWallToken],
	[CardIds.Colaque]: [CardIds.Colaque_ColaquesShellToken],
	[CardIds.CondemnRank1]: [CardIds.CondemnRank1_CondemnRank2Token, CardIds.CondemnRank1_CondemnRank3Token],
	[CardIds.ConditioningRank1]: [
		CardIds.ConditioningRank1_ConditioningRank2Token,
		CardIds.ConditioningRank1_ConditioningRank3Token,
	],
	[CardIds.ConfectionCyclone]: [CardIds.ConfectionCyclone_SugarElementalToken],
	[CardIds.ConvictionRank1]: [
		CardIds.ConvictionRank1_ConvictionRank2Token,
		CardIds.ConvictionRank1_ConvictionRank3Token,
	],
	[CardIds.CookieTheCook1]: [CardIds.CookieTheCook_CookiesStirringRodToken],
	[CardIds.Colaque]: [CardIds.Colaque_ColaquesShellToken],
	[CardIds.CommandTheElements]: [
		CardIds.CommandTheElements_LivingEarthToken,
		CardIds.CommandTheElements_StirTheStonesToken,
		CardIds.CommandTheElements_StormcallerBrukanToken,
		CardIds.CommandTheElements_TameTheFlamesToken,
	],
	[CardIds.ConjureManaBiscuit]: [CardIds.ConjureManaBiscuit_ManaBiscuitToken],
	[CardIds.CoralKeeper]: [CardIds.CoralKeeper_CoralElementalToken],
	[CardIds.Crabatoa]: [
		CardIds.Crabatoa_CrabatoasClawToken1,
		CardIds.Crabatoa_CrabatoasClawToken2,
		CardIds.Crabatoa_CrabatoaClawToken,
	],
	[CardIds.CurseOfAgony]: [CardIds.CurseOfAgony_AgonyToken],
	[CardIds.CthunTheShattered]: [
		CardIds.CthunTheShattered_BodyOfCthunToken,
		CardIds.CthunTheShattered_EyeOfCthunToken,
		CardIds.CthunTheShattered_HeartOfCthunToken,
		CardIds.CthunTheShattered_MawOfCthunToken,
	],
	[CardIds.DancingCobra]: [CardIds.DancingCobra_DancingCobraToken],
	[CardIds.DarkAlleyPact]: [CardIds.DarkAlleyPact_FiendToken],
	[CardIds.DarkbishopBenedictus]: [CardIds.Shadowform],
	[CardIds.DarkmoonDirigible]: [CardIds.DarkmoonDirigible_DarkmoonDirigibleToken],
	[CardIds.DarkmoonStatue]: [CardIds.DarkmoonStatue_DarkmoonStatueToken],
	[CardIds.DayAtTheFaire]: [CardIds.DayAtTheFaire_DayAtTheFaireToken, CardIds.SilverHandRecruitLegacyToken],
	[CardIds.DeathmatchPavilion]: [CardIds.DeathmatchPavilion_PavilionDuelistToken],
	[CardIds.DefendTheDwarvenDistrict]: [
		CardIds.DefendTheDwarvenDistrict_KnockEmDownToken,
		CardIds.DefendTheDwarvenDistrict_TakeTheHighGroundToken,
		CardIds.DefendTheDwarvenDistrict_TavishMasterMarksmanToken,
	],
	[CardIds.DerailedCoaster]: [CardIds.BumperCar_DarkmoonRiderToken],
	[CardIds.DeviateDreadfang]: [CardIds.DeviateDreadfang_DeviateViperToken],
	[CardIds.DevouringEctoplasm]: ADVENTURER_TOKENS,
	[CardIds.DemonicAssault]: [CardIds.VoidwalkerCore],
	[CardIds.DesecratedGraveyard]: [CardIds.DesecratedGraveyard_DesecratedShadeToken],
	[CardIds.DirewolfCommander]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.DireFrostwolf]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.DontFeedTheAnimals]: [CardIds.DontFeedTheAnimals_DontFeedTheAnimalsToken],
	[CardIds.DraggedBelow]: [CardIds.SirakessCultist_AbyssalCurseToken],
	[CardIds.DreadedMount]: [CardIds.DreadedMount_TamsinsDreadsteedToken],
	[CardIds.DreadlichTamsin1]: [
		CardIds.DreadlichTamsin_FelRiftToken,
		CardIds.DreadlichTamsin_DreadImpToken,
		CardIds.ChainsOfDread1,
	],
	[CardIds.DruidOfThePlains]: [CardIds.DruidOfThePlains_DruidOfThePlainsToken],
	[CardIds.DruidOfTheReef]: [CardIds.DruidOfTheReef_SeaTurtleForm, CardIds.DruidOfTheReef_SharkForm],
	[CardIds.DunkTank]: [CardIds.DunkTank_DunkTankToken],
	[CardIds.ElekkMount]: [CardIds.ElekkMount_XyrellasElekkToken],
	[CardIds.ElwynnBoar]: [CardIds.ElwynnBoar_SwordOfAThousandTruthsToken],
	[CardIds.ExpendablePerformers]: [CardIds.CoordinatedStrike_IllidariInitiateLegacyToken],
	[CardIds.FaireArborist]: [
		CardIds.FaireArborist_FaireArboristToken,
		CardIds.FaireArborist_TreantToken,
		CardIds.FaireArborist_PruneTheFruit,
	],
	[CardIds.FairgroundFool]: [CardIds.FairgroundFool_FairgroundFoolToken],
	[CardIds.FelsteelExecutioner]: [CardIds.FelsteelExecutioner_FelsteelExecutionerToken],
	[CardIds.FinalGasp]: ADVENTURER_TOKENS,
	[CardIds.FinalShowdown]: [
		CardIds.FinalShowdown_CloseThePortalToken,
		CardIds.FinalShowdown_GainMomentumToken,
		CardIds.DemonslayerKurtrusToken,
	],
	[CardIds.FindTheImposter]: [
		CardIds.FindTheImposter_FizzflashDistractorToken,
		CardIds.FindTheImposter_HiddenGyrobladeToken,
		CardIds.FindTheImposter_LearnTheTruthToken,
		CardIds.FindTheImposter_MarkedATraitorToken,
		CardIds.FindTheImposter_NoggenFogGeneratorToken,
		CardIds.FindTheImposter_SpyOMaticToken,
		CardIds.FindTheImposter_SpymasterScabbsToken,
	],
	[CardIds.FireworkElemental]: [CardIds.FireworkElemental_FireworkElementalToken],
	[CardIds.FirstFlame]: [CardIds.FirstFlame_SecondFlameToken],
	[CardIds.FlankingManeuver]: [CardIds.FlankingManeuver],
	[CardIds.FleethoofPearltusk]: [CardIds.FleethoofPearltusk_FleethoofPearltuskToken],
	[CardIds.FlightmasterDungar]: [
		CardIds.FlightmasterDungar_EasternPlaguelandsToken,
		CardIds.FlightmasterDungar_IronforgeToken,
		CardIds.FlightmasterDungar_WestfallToken,
	],
	[CardIds.FlipperFriends]: [CardIds.FlipperFriends_OrcaToken, CardIds.FlipperFriends_OtterToken],
	[CardIds.FrostweaveDungeoneer]: [CardIds.Rimetongue_FrostedElementalToken],
	[CardIds.FrostwolfKennels]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.FuryRank1]: [CardIds.FuryRank1_FuryRank2Token, CardIds.FuryRank1_FuryRank3Token],
	[CardIds.GaiaTheTechtonic]: [CardIds.GaiaTheTechtonic_GaiasDrillToken1, CardIds.GaiaTheTechtonic_GaiasDrillToken2],
	[CardIds.GallopingSavior]: [CardIds.GallopingSavior_HolySteedToken],
	[CardIds.Garrote]: [CardIds.Garrote_BleedToken],
	[CardIds.Gigafin]: [CardIds.Gigafin_GigafinsMawToken],
	[CardIds.GluggTheGulper]: [
		CardIds.GluggTheGulper_GluggsTailToken1,
		CardIds.GluggTheGulper_GluggsTailToken2,
		CardIds.GluggTheGulper_GluggsTailToken3,
	],
	[CardIds.GrandFinale]: [CardIds.GrandFinale_ExplodingSparklerToken],
	[CardIds.GrandMagusAntonidas]: [CardIds.FireballCore],
	[CardIds.HammerOfTheNaaru]: [CardIds.HammerOfTheNaaru_HolyElementalToken],
	[CardIds.HogRancher]: [CardIds.HogRancher_HogToken],
	[CardIds.HornOfWrathion]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.Hydralodon]: [CardIds.Hydralodon_HydralodonHeadToken1, CardIds.Hydralodon_HydralodonHeadToken2],
	[CardIds.Impfestation]: [CardIds.DreadlichTamsin_DreadImpToken],
	[CardIds.ImmortalizedInStone]: [
		CardIds.ImmortalizedInStone_LivingStatueToken,
		CardIds.ImmortalizedInStone_PristineStatueToken,
		CardIds.ImmortalizedInStone_WornStatueToken,
	],
	[CardIds.ImportedTarantula]: [CardIds.ImportedTarantula_InvasiveSpiderlingToken],
	[CardIds.ImpSwarmRank1]: [
		CardIds.ImpSwarmRank1_ImpSwarmRank2Token,
		CardIds.ImpSwarmRank1_ImpSwarmRank3Token,
		CardIds.ImpSwarmRank1_ImpFamiliarToken,
	],
	[CardIds.InsatiableFelhound]: [CardIds.InsatiableFelhound_InsatiableFelhoundToken],
	[CardIds.Insight]: [CardIds.Insight_InsightToken],
	[CardIds.KargalBattlescar1]: [CardIds.KargalBattlescar_LookoutToken],
	[CardIds.Kazakusan1]: [
		CardIds.NecroticPoison2,
		CardIds.Spyglass2,
		CardIds.ClockworkAssistant2,
		CardIds.GrimmerPatron2,
		CardIds.PuzzleBox2,
		CardIds.MutatingInjection2,
		CardIds.TheExorcisor2,
		CardIds.PureCold2,
		CardIds.Bubba2,
		CardIds.HolyBook2,
		CardIds.CrustyTheCrustacean2,
		CardIds.LoomingPresence2,
		CardIds.BeastlyBeauty2,
		CardIds.Hyperblaster2,
		CardIds.DrBoomsBoombox2,
		CardIds.WaxRager2,
		CardIds.VampiricFangs,
		CardIds.GnomishArmyKnife2,
		CardIds.Locuuuusts2,
		CardIds.Locuuuusts_LocuuuustsToken,
		CardIds.WandOfDisintegration2,
		CardIds.StaffOfScales2,
		CardIds.PhaorisBlade2,
		CardIds.ZephryssLamp2,
		CardIds.CanopicJars2,
		CardIds.AncientReflections2,
		CardIds.BananaSplit2,
		CardIds.EmbersOfRagnaros2,
		CardIds.BookOfTheDead2,
		CardIds.AnnoyOHorn2,
		CardIds.FlexPlosion2,
		CardIds.BladeOfQueldelar,
		CardIds.HiltOfQueldelar,
		CardIds.Queldelar2,
	],
	[CardIds.KazakusGolemShaper]: [
		CardIds.KazakusGolemShaper_EarthrootToken,
		CardIds.KazakusGolemShaper_FadeleafToken,
		CardIds.KazakusGolemShaper_FirebloomToken,
		CardIds.KazakusGolemShaper_GraveMossToken,
		CardIds.KazakusGolemShaper_GromsbloodToken,
		CardIds.KazakusGolemShaper_IcecapToken,
		CardIds.KazakusGolemShaper_KingsbloodToken,
		CardIds.KazakusGolemShaper_LiferootToken,
		CardIds.KazakusGolemShaper_MageroyalToken,
		CardIds.KazakusGolemShaper_SungrassToken,
		CardIds.KazakusGolemShaper_SwifthistleToken,
		CardIds.KazakusGolemShaper_WildvineToken,
	],
	[CardIds.KiriChosenOfElune]: [CardIds.SolarEclipse, CardIds.LunarEclipse],
	[CardIds.KoboldTaskmaster]: [CardIds.KoboldTaskmaster_ArmorScrapToken],
	[CardIds.KodoMount]: [CardIds.KodoMount_GuffsKodoToken],
	[CardIds.KolkarPackRunner]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.KreshLordOfTurtling]: [CardIds.KreshLordOfTurtling_TurtleSpikeToken],
	[CardIds.KurtrusDemonRender]: [
		CardIds.KurtrusDemonRender_AshfallensFury,
		CardIds.KurtrusDemonRender_FelbatShriekerToken,
	],
	[CardIds.LibramOfJudgment]: [CardIds.LibramOfJudgment_LibramOfJudgmentToken],
	[CardIds.LightforgedCariel]: [CardIds.LightforgedCariel_BlessingOfQueens, CardIds.TheImmovableObject],
	[CardIds.LilypadLurker]: [CardIds.FrogLegacy],
	[CardIds.LivingSeedRank1]: [
		CardIds.LivingSeedRank1_LivingSeedRank2Token,
		CardIds.LivingSeedRank1_LivingSeedRank3Token,
	],
	[CardIds.LoanShark]: [CardIds.TheCoin1],
	[CardIds.LostInThePark]: [
		CardIds.LostInThePark_DefendTheSquirrelsToken,
		CardIds.LostInThePark_FeralFriendsyToken,
		CardIds.LostInThePark_GuffTheToughToken,
	],
	[CardIds.LuckysoulHoarder]: [
		CardIds.LuckysoulHoarder_LuckysoulHoarderToken,
		CardIds.SchoolSpirits_SoulFragmentToken,
	],
	[CardIds.MagisterDawngrasp]: [CardIds.MagisterDawngrasp_ArcaneBurst],
	[CardIds.MailboxDancer]: [CardIds.TheCoin1],
	[CardIds.Mankrik]: [CardIds.Mankrik_OlgraMankriksWifeToken, CardIds.Mankrik_MankrikConsumedByHatredToken],
	[CardIds.MeetingStone]: ADVENTURER_TOKENS,
	[CardIds.MidaPureLight1]: [CardIds.MidaPureLight_FragmentOfMidaToken],
	[CardIds.MoontouchedAmulet]: [CardIds.MoontouchedAmulet_MoontouchedAmuletToken],
	[CardIds.MountainBear]: [CardIds.MountainBear_MountainCubToken],
	[CardIds.MorshanWatchPost]: [CardIds.MorshanWatchPost_WatchfulGruntToken],
	[CardIds.NagasPride]: [CardIds.NagasPride_LionfishToken],
	[CardIds.NeeruFireblade1]: [CardIds.NeeruFireblade_BurningBladePortalToken, CardIds.RingMatron_FieryImpToken],
	[CardIds.NellieTheGreatThresher]: [CardIds.NellieTheGreatThresher_NelliesPirateShipToken],
	[CardIds.NobleMount]: [CardIds.NobleMount_CarielsWarhorseToken],
	[CardIds.OasisAlly]: [CardIds.WaterElemental3],
	[CardIds.OnyxianWarder]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.OpenTheCages]: ANIMAL_COMPANION_TOKENS,
	[CardIds.PettingZoo]: [CardIds.PettingZoo_DarkmoonStrider],
	[CardIds.PitMaster]: [CardIds.PitMaster_PitMasterToken, CardIds.PitMaster_DuelistToken],
	[CardIds.RenownedPerformer]: [CardIds.RenownedPerformer_PerformersAssistantToken],
	[CardIds.RingMatron]: [CardIds.RingMatron_FieryImpToken],
	[CardIds.RingToss1]: [CardIds.RingToss_RingTossToken1],
	[CardIds.RingToss2]: [CardIds.RingToss_RingTossToken2],
	[CardIds.RokaraTheValorous]: [
		CardIds.RokaraTheValorous_GrandSlam,
		CardIds.RokaraTheValorous_TheUnstoppableForceToken,
	],
	[CardIds.PartyUp]: ADVENTURER_TOKENS,
	[CardIds.PiranhaPoacher]: PIRANHA_TOKENS,
	[CardIds.PiggybackImp]: [CardIds.PiggybackImp_BackpiggyImpToken],
	[CardIds.PirateAdmiralHooktusk]: [
		CardIds.PirateAdmiralHooktusk_TakeTheirGoldToken,
		CardIds.PirateAdmiralHooktusk_TakeTheirShipToken,
		CardIds.PirateAdmiralHooktusk_TakeTheirSuppliesToken,
	],
	[CardIds.ProtectTheInnocent]: [CardIds.ProtectTheInnocent_StormpikeDefenderToken],
	[CardIds.QueenAzshara2]: [
		CardIds.RingOfTides,
		CardIds.HornOfAncients,
		CardIds.Xalatath,
		CardIds.TidestoneOfGolganneth,
	],
	[CardIds.RaidBossOnyxia1]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.RaidTheDocks]: [
		CardIds.RaidTheDocks_CreateADistractionToken,
		CardIds.RaidTheDocks_SecureTheSuppliesToken,
		CardIds.RaidTheDocks_CapnRokaraToken,
		CardIds.RaidTheDocks_TheJuggernautToken,
	],
	[CardIds.RamCommander]: [CardIds.RamCommander_BattleRamToken],
	[CardIds.RammingMount]: [CardIds.RammingMount_TavishsRamToken],
	[CardIds.RatsOfExtraordinarySize]: [CardIds.RatPack_RatToken],
	[CardIds.Reefwalker]: PIRANHA_TOKENS,
	[CardIds.RemoteControlledGolem]: [CardIds.RemoteControlledGolem_GolemPartsToken],
	[CardIds.RodentNest]: [CardIds.RodentNest_RatToken],
	[CardIds.Rimetongue]: [CardIds.Rimetongue_FrostedElementalToken],
	[CardIds.RiseToTheOccasion]: [
		CardIds.RiseToTheOccasion_AvengeTheFallenToken,
		CardIds.RiseToTheOccasion_PaveTheWayToken,
		CardIds.RiseToTheOccasion_LightbornCarielToken,
		CardIds.LightsJusticeLegacy,
	],
	[CardIds.ScaleOfOnyxia]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.Scrapsmith]: [CardIds.Scrapsmith_ScrappyGruntToken],
	[CardIds.Schooling]: PIRANHA_TOKENS,
	[CardIds.SchoolTeacher]: [CardIds.SchoolTeacher_NagalingToken],
	[CardIds.SeascoutOperator]: [CardIds.SeascoutOperator_MechafishToken],
	[CardIds.SeedsOfDestruction]: [CardIds.DreadlichTamsin_FelRiftToken, CardIds.DreadlichTamsin_DreadImpToken],
	[CardIds.SeekGuidance]: [
		CardIds.SeekGuidance_DiscoverTheVoidShardToken,
		CardIds.SeekGuidance_IlluminateTheVoidToken,
		CardIds.SeekGuidance_XyrellaTheSanctifiedToken,
	],
	[CardIds.ShadowcrafterScabbs]: [CardIds.ShadowcrafterScabbs_SleightOfHand, CardIds.ShadowcrafterScabbs_ShadowToken],
	[CardIds.Shenanigans]: [CardIds.BananaBuffoon_BananasToken],
	[CardIds.SigilOfSummoning]: [CardIds.SigilOfSummoning_WailingDemonToken],
	[CardIds.SindoreiScentfinder]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.SirakessCultist]: [CardIds.SirakessCultist_AbyssalCurseToken],
	[CardIds.Sleetbreaker]: [CardIds.Windchill1],
	[CardIds.SoldiersCaravan]: [CardIds.SilverHandRecruitLegacyToken],
	[CardIds.SorcerersGambit]: [
		CardIds.SorcerersGambit_StallForTimeToken,
		CardIds.SorcerersGambit_ReachThePortalRoomToken,
		CardIds.SorcerersGambit_ArcanistDawngraspToken,
	],
	[CardIds.SowTheSoil]: [CardIds.SowTheSoil_TreantToken],
	[CardIds.SpawnpoolForager]: [CardIds.SpawnpoolForager_DiremuckTinyfinToken],
	[CardIds.SpiritAlpha]: [CardIds.SpiritWolfLegacy],
	[CardIds.SpiritJailer1]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.SpiritJailer2]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.SpiritMount]: [CardIds.SpiritMount_BrukansRaptorToken],
	[CardIds.StageDive]: [CardIds.StageDive_StageDive],
	[CardIds.Strongman]: [CardIds.Strongman_StrongmanToken],
	[CardIds.SweetTooth]: [CardIds.SweetTooth_SweetTooth],
	[CardIds.SwordEater]: [CardIds.SwordEater_JawbreakerToken],
	[CardIds.TameBeastRank1]: [
		CardIds.TameBeastRank1_TameBeastRank2Token,
		CardIds.TameBeastRank1_TameBeastRank3Token,
		CardIds.TameBeastRank1_TamedCrabToken,
		CardIds.TameBeastRank1_TamedScorpidToken,
		CardIds.TameBeastRank1_TamedThunderLizardToken,
	],
	[CardIds.TheDemonSeed]: [
		CardIds.TheDemonSeed_CompleteTheRitualToken,
		CardIds.TheDemonSeed_EstablishTheLinkToken,
		CardIds.TheDemonSeed_BlightbornTamsinToken,
	],
	[CardIds.TheLeviathan]: [CardIds.TheLeviathan_TheLeviathansClawToken],
	[CardIds.ThorngrowthSentries]: [CardIds.ThorngrowthSentries_ThornguardTurtleToken],
	[CardIds.Tickatus]: [CardIds.Tickatus_TickatusToken],
	[CardIds.TicketMaster]: [CardIds.TicketMaster_TicketsToken, CardIds.TicketMaster_PlushBearToken],
	[CardIds.VeteranWarmedic]: [CardIds.VeteranWarmedic_BattlefieldMedicToken],
	[CardIds.VibrantSquirrel]: [CardIds.VibrantSquirrel_AcornToken, CardIds.VibrantSquirrel_SatisfiedSquirrelToken],
	[CardIds.VileCall]: [CardIds.VileCall_RavenousVilefiendToken],
	[CardIds.WickedShipment]: [CardIds.ImpGangBoss_ImpToken],
	[CardIds.WickedStabRank1]: [
		CardIds.WickedStabRank1_WickedStabRank2Token,
		CardIds.WickedStabRank1_WickedStabRank3Token,
	],
	[CardIds.WildpawCavern]: [CardIds.BearonGlashear_FrozenStagguardToken],
	[CardIds.WildheartGuff]: [CardIds.WildheartGuff_Nurture],
	[CardIds.WingCommanderMulverick]: [CardIds.WingCommanderMulverick_StrikeWyvernToken],
	[CardIds.WingsOfHateRank1]: [
		CardIds.WingsOfHateRank1_WingsOfHateRank2Token,
		CardIds.WingsOfHateRank1_WingsOfHateRank3Token,
		CardIds.Umberwing_FelwingToken,
	],
	[CardIds.WoundPrey]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.XhilagOfTheAbyss]: [
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken1,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken2,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken3,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken4,
	],
	[CardIds.XyrellaTheDevout]: [CardIds.XyrellaTheDevout_HolyTouch, CardIds.XyrellaTheDevout_VoidSpike],
	[CardIds.YoggSaronMasterOfFate]: [
		CardIds.YoggSaronMasterOfFate_CurseOfFleshToken,
		CardIds.YoggSaronMasterOfFate_DevouringHungerToken,
		CardIds.YoggSaronMasterOfFate_HandOfFateToken,
		CardIds.YoggSaronMasterOfFate_MindflayerGogglesToken,
		CardIds.YoggSaronMasterOfFate_MysteryboxToken,
		CardIds.YoggSaronMasterOfFate_RodOfRoastingToken,
	],
	[CardIds.YseraLegacy]: DREAM_CARDS,
	[CardIds.YseraVanilla]: [
		CardIds.DreamVanilla,
		CardIds.EmeraldDrakeVanilla,
		CardIds.LaughingSisterVanilla,
		CardIds.NightmareVanilla,
		CardIds.YseraAwakensVanilla,
	],
	[CardIds.Zaqul]: [CardIds.SirakessCultist_AbyssalCurseToken],

	[CardIds.SneakyDelinquent]: [CardIds.SneakyDelinquent_SpectralDelinquentToken],
	[CardIds.SoulShear1]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.SoulShear2]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.SchoolSpirits1]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.SchoolSpirits2]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.Marrowslicer]: [CardIds.SchoolSpirits_SoulFragmentToken],
	[CardIds.BloatedPython]: [CardIds.BloatedPython_HaplessHandlerToken],
	[CardIds.CeremonialMaul]: [CardIds.CeremonialMaul_HonorStudentToken],
	[CardIds.MoltenBlast]: [CardIds.MoltenBlast_MoltenElementalToken],
	[CardIds.DisciplinarianGandling]: [CardIds.DisciplinarianGandling_FailedStudentToken],
	[CardIds.FishyFlyer]: [CardIds.FishyFlyer_SpectralFlyerToken],
	[CardIds.InfiltratorLilian]: [CardIds.InfiltratorLilian_ForsakenLilianToken],
	[CardIds.VilefiendTrainer]: [CardIds.VilefiendTrainer_SnarlingVilefiendToken],
	[CardIds.WyrmWeaver]: [CardIds.ManaWyrmLegacy],
	[CardIds.Ogremancer]: [CardIds.Ogremancer_RisenSkeletonToken],
	[CardIds.TotemGoliath]: [
		CardIds.StoneclawTotem,
		CardIds.HealingTotem,
		CardIds.SearingTotemLegacy,
		CardIds.StrengthTotem,
	],
	[CardIds.Vectus]: [CardIds.Vectus_PlaguedHatchlingToken],
	[CardIds.RunicCarvings]: [
		CardIds.RunicCarvings_AlarmTheForest,
		CardIds.RunicCarvings_CallToAid,
		CardIds.RunicCarvings_TreantTotemToken,
	],
	[CardIds.SmugSenior]: [CardIds.SmugSenior_SpectralSeniorToken],
	[CardIds.CycleOfHatred]: [CardIds.CycleOfHatred_SpiritOfVengeanceToken],
	[CardIds.FelGuardians]: [CardIds.FelGuardians_SoulfedFelhoundToken],
	[CardIds.SoulciologistMalicia]: [CardIds.SoulciologistMalicia_ReleasedSoulToken],
	[CardIds.Troublemaker]: [CardIds.Troublemaker_RuffianToken],
	[CardIds.ImprisonedGanarg]: [CardIds.FieryWarAxeCore],
	[CardIds.ImprisonedSungill]: [CardIds.ImprisonedSungill_SungillStreamrunnerToken],
	[CardIds.ReliquaryOfSouls]: [CardIds.ReliquaryOfSouls_ReliquaryPrimeToken],
	[CardIds.Ambush]: [CardIds.Ambush_BrokenAmbusherToken],
	[CardIds.AstromancerSolarian]: [CardIds.AstromancerSolarian_SolarianPrimeToken],
	[CardIds.KanrethadEbonlocke]: [CardIds.KanrethadEbonlocke_KanrethadPrimeToken],
	[CardIds.MurgurMurgurgle]: [CardIds.MurgurMurgurgle_MurgurglePrimeToken],
	[CardIds.RustswornInitiate]: [CardIds.RustswornInitiate_ImpcasterToken],
	[CardIds.Akama1]: [CardIds.Akama_AkamaPrimeToken],
	[CardIds.ArchsporeMsshifn]: [CardIds.ArchsporeMsshifn_MsshifnPrimeToken],
	[CardIds.BlisteringRot]: [CardIds.BlisteringRot_LivingRotToken],
	[CardIds.LadyVashj1]: [CardIds.LadyVashj_VashjPrimeToken],
	[CardIds.TerrorguardEscapee]: [CardIds.TerrorguardEscapee_HuntressToken],
	[CardIds.ZixorApexPredator]: [CardIds.ZixorApexPredator_ZixorPrimeToken],
	[CardIds.DisguisedWanderer]: [CardIds.DisguisedWanderer_RustswornInquisitorToken],
	[CardIds.KargathBladefist1]: [CardIds.KargathBladefist_KargathPrimeToken],
	[CardIds.Magtheridon1]: [CardIds.Magtheridon_HellfireWarderToken],
	[CardIds.RustswornCultist]: [CardIds.RustswornCultist_RustedDevilToken],
	[CardIds.Alar]: [CardIds.Alar_AshesOfAlarToken],
	[CardIds.GlowflySwarm]: [CardIds.GlowflySwarm_GlowflyToken],
	[CardIds.LibramOfJustice1]: [CardIds.LibramOfJustice_OverdueJusticeToken],
	[CardIds.Metamorphosis1]: [CardIds.Metamorphosis_DemonicBlast1],
	[CardIds.Metamorphosis2]: [CardIds.Metamorphosis_DemonicBlast1],
	[CardIds.MetamorphosisCore]: [CardIds.Metamorphosis_DemonicBlast1],
	[CardIds.DragonmawSkyStalker]: [CardIds.DragonmawSkyStalker_DragonriderToken],
	[CardIds.CursedVagrant]: [CardIds.CursedVagrant_CursedShadowToken],
	[CardIds.CoilfangWarlord]: [CardIds.CoilfangWarlord_ConchguardWarlordToken],
	[CardIds.DeepFreeze]: [CardIds.WaterElemental3],
	[CardIds.EnhancedDreadlord]: [CardIds.EnhancedDreadlord_DesperateDreadlordToken],
	[CardIds.LibramOfHope]: [CardIds.LibramOfHope_AncientGuardianToken],
	[CardIds.NagrandSlam]: [CardIds.NagrandSlam_ClefthoofToken],
	[CardIds.ScrapyardColossus]: [CardIds.ScrapyardColossus_FelcrackedColossusToken],
	[CardIds.TwinSlice1]: [CardIds.TwinSlice_SecondSliceToken],
	[CardIds.UrzulHorror]: [CardIds.UrzulHorror_LostSoulToken],
	[CardIds.Umberwing]: [CardIds.Umberwing_FelwingToken],
	[CardIds.CommandTheIllidari]: [CardIds.CoordinatedStrike_IllidariInitiateLegacyToken],
	[CardIds.AirRaid1]: [CardIds.SilverHandRecruitLegacyToken],
	[CardIds.LicensedAdventurer]: [CardIds.TheCoin1],
	[CardIds.RisingWinds]: [CardIds.RisingWinds_EagleToken],
	[CardIds.BombWrangler]: [CardIds.DrBoom_BoomBotToken],
	[CardIds.GrandLackeyErkh]: LACKEY_TOKENS,
	[CardIds.WhispersOfEvil]: LACKEY_TOKENS,
	[CardIds.EvilQuartermaster]: LACKEY_TOKENS,
	[CardIds.SkyGenralKragg]: [CardIds.SkyGenralKragg_SharkbaitToken],
	[CardIds.Hailbringer]: [CardIds.Hailbringer_IceShardToken],
	[CardIds.EyeOfTheStorm]: [CardIds.EyeOfTheStorm_StormblockerToken],
	[CardIds.TheAmazingReno1]: [CardIds.TheAmazingReno_WhatDoesThisDoquestionHeroic],
	[CardIds.BloodsailFlybooter]: [CardIds.BloodsailFlybooter_SkyPirateToken],
	[CardIds.ClearTheWay]: [CardIds.ClearTheWay_GryphonToken],
	[CardIds.LearnDraconic]: [CardIds.LearnDraconic_DraconicEmissaryToken],
	[CardIds.SecureTheDeck]: [CardIds.ClawLegacy],
	[CardIds.ToxicReinforcements]: [CardIds.ToxicReinforcements_LeperGnomeToken],
	[CardIds.Treenforcements]: [
		CardIds.Treenforcements_SmallRepairs,
		CardIds.Treenforcements_SpinEmUp,
		CardIds.Treenforcements_TreantToken,
	],
	[CardIds.VioletSpellwing]: [CardIds.ArcaneMissilesLegacy],
	[CardIds.Sanctuary]: [CardIds.Sanctuary_IndomitableChampionToken],
	[CardIds.Shrubadier]: [CardIds.Treenforcements_TreantToken],
	[CardIds.BadLuckAlbatross]: [CardIds.BadLuckAlbatross_AlbatrossToken],
	[CardIds.Chenvaala]: [CardIds.Chenvaala_SnowElementalToken],
	[CardIds.SkyClaw]: [CardIds.SkyClaw_MicrocopterToken],
	[CardIds.LightforgedZealot]: [CardIds.LightforgedZealot_TruesilverChampionToken],
	[CardIds.MalygosAspectOfMagic]: [
		CardIds.MalygosAspectOfMagic_MalygossIntellectToken,
		CardIds.MalygosAspectOfMagic_MalygossMissilesToken,
		CardIds.MalygosAspectOfMagic_MalygossTomeToken,
		CardIds.MalygosAspectOfMagic_MalygossExplosionToken,
		CardIds.MalygosAspectOfMagic_MalygossNovaToken,
		CardIds.MalygosAspectOfMagic_MalygossPolymorphToken,
		CardIds.MalygossPolymorph_MalygossSheepToken,
		CardIds.MalygosAspectOfMagic_MalygossFlamestrikeToken,
		CardIds.MalygosAspectOfMagic_MalygossFrostboltToken,
		CardIds.MalygosAspectOfMagic_MalygossFireballToken,
	],
	[CardIds.Waxadred]: [CardIds.Waxadred_WaxadredsCandleToken],
	[CardIds.AbyssalSummoner]: [CardIds.AbyssalSummoner_AbyssalDestroyerToken],
	[CardIds.KronxDragonhoof]: [
		CardIds.KronxDragonhoof_DecimationToken,
		CardIds.KronxDragonhoof_ReanimationToken,
		CardIds.KronxDragonhoof_DominationToken,
		CardIds.KronxDragonhoof_AnnihilationToken,
	],
	[CardIds.Nithogg]: [CardIds.Nithogg_StormEggToken, CardIds.Nithogg_StormDrakeToken],
	[CardIds.GalakrondTheNightmare]: [
		CardIds.GalakrondTheNightmare_GalakrondTheApocalypseToken,
		CardIds.GalakrondTheNightmare_GalakrondAzerothsEndToken,
		CardIds.GalakrondsGuile,
	],
	[CardIds.GalakrondTheTempest]: [
		CardIds.GalakrondTheTempest_GalakrondTheApocalypseToken,
		CardIds.GalakrondTheTempest_GalakrondAzerothsEndToken,
		CardIds.GalakrondsFury,
	],
	[CardIds.GalakrondTheUnbreakable]: [
		CardIds.GalakrondTheUnbreakable_GalakrondTheApocalypseToken,
		CardIds.GalakrondTheUnbreakable_GalakrondAzerothsEndToken,
		CardIds.GalakrondsMight,
	],
	[CardIds.GalakrondTheUnspeakable]: [
		CardIds.GalakrondTheUnspeakable_GalakrondTheApocalypseToken,
		CardIds.GalakrondTheUnspeakable_GalakrondAzerothsEndToken,
		CardIds.GalakrondsWit,
	],
	[CardIds.GalakrondTheWretched]: [
		CardIds.GalakrondTheWretched_GalakrondTheApocalypseToken,
		CardIds.GalakrondTheWretched_GalakrondAzerothsEndToken,
		CardIds.GalakrondsMalice,
		CardIds.DraconicImpToken,
	],
	[CardIds.Shuma]: [CardIds.Shuma_TentacleToken],
	[CardIds.ZzerakuTheWarped]: [CardIds.ZzerakuTheWarped_NetherDrakeToken],
	[CardIds.YseraUnleashed]: [CardIds.YseraUnleashed_DreamPortalToken],
};
