import { CardIds } from 'src/card-ids';
import { ReferenceCard } from 'src/public-api';

const PIRANHA_TOKENS = [
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken1,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken2,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken3,
	CardIds.PiranhaSwarmer_PiranhaSwarmerToken4,
];
const ADVENTURER_TOKENS = [
	CardIds.PartyUp_BurlyAdventurerToken,
	CardIds.PartyUp_ArcaneAdventurerToken,
	CardIds.PartyUp_DeadlyAdventurerToken,
	CardIds.PartyUp_DevoutAdventurerToken,
	CardIds.PartyUp_RelentlessAdventurerToken,
	CardIds.PartyUp_SneakyAdventurerToken,
	CardIds.PartyUp_SwiftAdventurerToken,
	CardIds.PartyUp_VitalAdventurerToken,
];
const DREAM_CARDS = [
	CardIds.DreamLegacy,
	CardIds.EmeraldDrakeLegacy,
	CardIds.LaughingSisterLegacy,
	CardIds.NightmareLegacy,
	CardIds.YseraAwakensLegacy,
];

export type RelatedCardExtractor = (cards: readonly ReferenceCard[]) => readonly string[];

export const RELATED_CARDS_DATA: {
	[cardId: string]: readonly (string | RelatedCardExtractor)[];
} = {
	[CardIds.AbyssalWave]: [CardIds.SirakessCultist_AbyssalCurseToken],
	// [CardIds.ApothecaryHelbrim]: [
	// 	CardIds.DeadlyPoisonCore,
	// 	CardIds.LeechingPoison,
	// 	CardIds.NitroboostPoison,
	// 	CardIds.ParalyticPoison,
	// 	CardIds.SilverleafPoison,
	// ], // Generation depends on the game mode you're playing (incl Arena / Duels probably)
	[CardIds.ArcaneOverflow]: [CardIds.ArcaneOverflow_ArcaneRemnantToken],
	[CardIds.ArchdruidNaralex]: DREAM_CARDS,
	[CardIds.AzsharanDefector]: [CardIds.AzsharanDefector_SunkenDefectorToken],
	[CardIds.AzsharanGardens]: [CardIds.AzsharanGardens_SunkenGardensToken],
	[CardIds.AzsharanMooncatcher]: [CardIds.AzsharanMooncatcher_SunkenMooncatcherToken],
	[CardIds.AzsharanRitual]: [CardIds.AzsharanRitual_SunkenRitualToken],
	[CardIds.AzsharanSaber]: [CardIds.AzsharanSaber_SunkenSaberToken],
	[CardIds.AzsharanScavenger]: [CardIds.AzsharanScavenger_SunkenScavengerToken],
	[CardIds.AzsharanScroll]: [CardIds.AzsharanScroll_SunkenScrollToken],
	[CardIds.AzsharanSentinel]: [CardIds.AzsharanSentinel_SunkenSentinelToken],
	[CardIds.AzsharanSweeper]: [CardIds.AzsharanSweeper_SunkenSweeperToken],
	[CardIds.AzsharanTrident]: [CardIds.AzsharanTrident_SunkenTridentToken],
	[CardIds.AzsharanVessel]: [
		CardIds.AzsharanVessel_SunkenVesselToken,
		CardIds.AzsharanVessel_AzsharanPirateToken,
		CardIds.AzsharanVessel_SunkenPirateToken,
	],
	[CardIds.BattlewornVanguard]: [CardIds.Umberwing_FelwingToken],
	[CardIds.BearonGlashear]: [CardIds.BearonGlashear_FrozenStagguardToken],
	[CardIds.BeaststalkerTavish]: [
		CardIds.BeaststalkerTavish_ImprovedExplosiveTrapToken,
		CardIds.BeaststalkerTavish_ImprovedFreezingTrapToken,
		CardIds.BeaststalkerTavish_ImprovedIceTrapToken,
		CardIds.BeaststalkerTavish_ImprovedOpenTheCagesToken,
		CardIds.BeaststalkerTavish_ImprovedPackTacticsToken,
		CardIds.BeaststalkerTavish_ImprovedSnakeTrapToken,
		CardIds.BeaststalkerTavish_SummonPet,
	],
	[CardIds.BestInShell]: [CardIds.BestInShell_GoldshellTurtleToken],
	[CardIds.BlackscaleBrute]: [CardIds.BlackscaleBrute_FirescaleBerserkerToken],
	[CardIds.BlackwaterBehemoth]: [CardIds.BlackwaterBehemoth_BehemothsLureToken],
	[CardIds.BloodInTheWater]: [CardIds.BloodInTheWater_TigerSharkToken],
	[CardIds.BuildASnowman]: [
		CardIds.BuildASnowman_BuildASnowbruteToken,
		CardIds.BuildASnowman_BuildASnowgreToken,
		CardIds.BuildASnowman_SnowbruteToken,
		CardIds.BuildASnowman_SnowgreToken,
		CardIds.BuildASnowman_SnowmanToken,
	],
	[CardIds.BurningBladeAcolyte]: [CardIds.BurningBladeAcolyte_DemonspawnToken],
	[CardIds.BrukanOfTheElements]: [
		CardIds.BrukanOfTheElements_ElementalMastery,
		CardIds.ElementalMastery_EarthInvocationToken,
		CardIds.ElementalMastery_FireInvocationToken,
		CardIds.ElementalMastery_LightningInvocationToken,
		CardIds.ElementalMastery_CommandTheElementsToken,
		CardIds.BrukanOfTheElements_EarthInvocationToken,
		CardIds.BrukanOfTheElements_WaterInvocation,
		CardIds.BrukanOfTheElements_WaterInvocationToken,
		CardIds.BrukanOfTheElements_FireInvocationToken,
		CardIds.BrukanOfTheElements_LightningInvocationToken,
		CardIds.BrukanOfTheElements_EarthenGuardianToken,
	],
	[CardIds.CannonmasterSmythe1]: [CardIds.CannonmasterSmythe_NorthwatchSoldierToken],
	[CardIds.ChainLightningRank1]: [
		CardIds.ChainLightningRank1_ChainLightningRank2Token,
		CardIds.ChainLightningRank1_ChainLightningRank3Token,
	],
	[CardIds.CityArchitect]: [CardIds.CityArchitect_CastleWallToken],
	[CardIds.Colaque]: [CardIds.Colaque_ColaquesShellToken],
	[CardIds.CondemnRank1]: [CardIds.CondemnRank1_CondemnRank2Token, CardIds.CondemnRank1_CondemnRank3Token],
	[CardIds.ConditioningRank1]: [
		CardIds.ConditioningRank1_ConditioningRank2Token,
		CardIds.ConditioningRank1_ConditioningRank3Token,
	],
	[CardIds.ConvictionRank1]: [
		CardIds.ConvictionRank1_ConvictionRank2Token,
		CardIds.ConvictionRank1_ConvictionRank3Token,
	],
	[CardIds.CookieTheCook1]: [CardIds.CookieTheCook_CookiesStirringRodToken],
	[CardIds.Colaque]: [CardIds.Colaque_ColaquesShellToken],
	[CardIds.CommandTheElements]: [
		CardIds.CommandTheElements_LivingEarthToken,
		CardIds.CommandTheElements_StirTheStonesToken,
		CardIds.CommandTheElements_StormcallerBrukanToken,
		CardIds.CommandTheElements_TameTheFlamesToken,
	],
	[CardIds.CoralKeeper]: [CardIds.CoralKeeper_CoralElementalToken],
	[CardIds.Crabatoa]: [
		CardIds.Crabatoa_CrabatoasClawToken1,
		CardIds.Crabatoa_CrabatoasClawToken2,
		CardIds.Crabatoa_CrabatoaClawToken,
	],
	[CardIds.CurseOfAgony]: [CardIds.CurseOfAgony_AgonyToken],
	[CardIds.DarkAlleyPact]: [CardIds.DarkAlleyPact_FiendToken],
	[CardIds.DarkbishopBenedictus]: [CardIds.Shadowform],
	[CardIds.DefendTheDwarvenDistrict]: [
		CardIds.DefendTheDwarvenDistrict_KnockEmDownToken,
		CardIds.DefendTheDwarvenDistrict_TakeTheHighGroundToken,
		CardIds.DefendTheDwarvenDistrict_TavishMasterMarksmanToken,
	],
	[CardIds.DeviateDreadfang]: [CardIds.DeviateDreadfang_DeviateViperToken],
	[CardIds.DevouringEctoplasm]: ADVENTURER_TOKENS,
	[CardIds.DemonicAssault]: [CardIds.VoidwalkerCore],
	[CardIds.DesecratedGraveyard]: [CardIds.DesecratedGraveyard_DesecratedShadeToken],
	[CardIds.DirewolfCommander]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.DireFrostwolf]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.DraggedBelow]: [CardIds.SirakessCultist_AbyssalCurseToken],
	[CardIds.DreadedMount]: [CardIds.DreadedMount_TamsinsDreadsteedToken],
	[CardIds.DreadlichTamsin1]: [
		CardIds.DreadlichTamsin_FelRiftToken,
		CardIds.DreadlichTamsin_DreadImpToken,
		CardIds.ChainsOfDread1,
	],
	[CardIds.DruidOfThePlains]: [CardIds.DruidOfThePlains_DruidOfThePlainsToken],
	[CardIds.DruidOfTheReef]: [CardIds.DruidOfTheReef_SeaTurtleForm, CardIds.DruidOfTheReef_SharkForm],
	[CardIds.ElekkMount]: [CardIds.ElekkMount_XyrellasElekkToken],
	[CardIds.ElwynnBoar]: [CardIds.ElwynnBoar_SwordOfAThousandTruthsToken],
	[CardIds.FinalGasp]: ADVENTURER_TOKENS,
	[CardIds.FinalShowdown]: [
		CardIds.FinalShowdown_CloseThePortalToken,
		CardIds.FinalShowdown_GainMomentumToken,
		CardIds.DemonslayerKurtrusToken,
	],
	[CardIds.FindTheImposter]: [
		CardIds.FindTheImposter_FizzflashDistractorToken,
		CardIds.FindTheImposter_HiddenGyrobladeToken,
		CardIds.FindTheImposter_LearnTheTruthToken,
		CardIds.FindTheImposter_MarkedATraitorToken,
		CardIds.FindTheImposter_NoggenFogGeneratorToken,
		CardIds.FindTheImposter_SpyOMaticToken,
		CardIds.FindTheImposter_SpymasterScabbsToken,
	],
	[CardIds.FirstFlame]: [CardIds.FirstFlame_SecondFlameToken],
	[CardIds.FlankingManeuver]: [CardIds.FlankingManeuver],
	[CardIds.FlightmasterDungar]: [
		CardIds.FlightmasterDungar_EasternPlaguelandsToken,
		CardIds.FlightmasterDungar_IronforgeToken,
		CardIds.FlightmasterDungar_WestfallToken,
	],
	[CardIds.FlipperFriends]: [CardIds.FlipperFriends_OrcaToken, CardIds.FlipperFriends_OtterToken],
	[CardIds.FrostweaveDungeoneer]: [CardIds.Rimetongue_FrostedElementalToken],
	[CardIds.FrostwolfKennels]: [CardIds.DireFrostwolf_FrostwolfCubToken],
	[CardIds.FuryRank1]: [CardIds.FuryRank1_FuryRank2Token, CardIds.FuryRank1_FuryRank3Token],
	[CardIds.GaiaTheTechtonic]: [CardIds.GaiaTheTechtonic_GaiasDrillToken1, CardIds.GaiaTheTechtonic_GaiasDrillToken2],
	[CardIds.GallopingSavior]: [CardIds.GallopingSavior_HolySteedToken],
	[CardIds.Garrote]: [CardIds.Garrote_BleedToken],
	[CardIds.Gigafin]: [CardIds.Gigafin_GigafinsMawToken],
	[CardIds.GluggTheGulper]: [
		CardIds.GluggTheGulper_GluggsTailToken1,
		CardIds.GluggTheGulper_GluggsTailToken2,
		CardIds.GluggTheGulper_GluggsTailToken3,
	],
	[CardIds.GrandMagusAntonidas]: [CardIds.FireballCore],
	[CardIds.HogRancher]: [CardIds.HogRancher_HogToken],
	[CardIds.HornOfWrathion]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.Hydralodon]: [CardIds.Hydralodon_HydralodonHeadToken1, CardIds.Hydralodon_HydralodonHeadToken2],
	[CardIds.ImmortalizedInStone]: [
		CardIds.ImmortalizedInStone_LivingStatueToken,
		CardIds.ImmortalizedInStone_PristineStatueToken,
		CardIds.ImmortalizedInStone_WornStatueToken,
	],
	[CardIds.Impfestation]: [CardIds.DreadlichTamsin_DreadImpToken],
	[CardIds.ImpSwarmRank1]: [
		CardIds.ImpSwarmRank1_ImpSwarmRank2Token,
		CardIds.ImpSwarmRank1_ImpSwarmRank3Token,
		CardIds.ImpSwarmRank1_ImpFamiliarToken,
	],
	[CardIds.ImportedTarantula]: [CardIds.ImportedTarantula_InvasiveSpiderlingToken],
	[CardIds.KargalBattlescar1]: [CardIds.KargalBattlescar_LookoutToken],
	[CardIds.Kazakusan1]: [
		CardIds.NecroticPoison2,
		CardIds.Spyglass2,
		CardIds.ClockworkAssistant2,
		CardIds.GrimmerPatron2,
		CardIds.PuzzleBox2,
		CardIds.MutatingInjection2,
		CardIds.TheExorcisor2,
		CardIds.PureCold2,
		CardIds.Bubba2,
		CardIds.HolyBook2,
		CardIds.CrustyTheCrustacean2,
		CardIds.LoomingPresence2,
		CardIds.BeastlyBeauty2,
		CardIds.Hyperblaster2,
		CardIds.DrBoomsBoombox2,
		CardIds.WaxRager2,
		CardIds.VampiricFangs,
		CardIds.GnomishArmyKnife2,
		CardIds.Locuuuusts2,
		CardIds.Locuuuusts_LocuuuustsToken,
		CardIds.WandOfDisintegration2,
		CardIds.StaffOfScales2,
		CardIds.PhaorisBlade2,
		CardIds.ZephryssLamp2,
		CardIds.CanopicJars2,
		CardIds.AncientReflections2,
		CardIds.BananaSplit2,
		CardIds.EmbersOfRagnaros2,
		CardIds.BookOfTheDead2,
		CardIds.AnnoyOHorn2,
		CardIds.FlexPlosion2,
		CardIds.BladeOfQueldelar,
		CardIds.HiltOfQueldelar,
		CardIds.Queldelar2,
	],
	[CardIds.KazakusGolemShaper]: [
		CardIds.KazakusGolemShaper_EarthrootToken,
		CardIds.KazakusGolemShaper_FadeleafToken,
		CardIds.KazakusGolemShaper_FirebloomToken,
		CardIds.KazakusGolemShaper_GraveMossToken,
		CardIds.KazakusGolemShaper_GromsbloodToken,
		CardIds.KazakusGolemShaper_IcecapToken,
		CardIds.KazakusGolemShaper_KingsbloodToken,
		CardIds.KazakusGolemShaper_LiferootToken,
		CardIds.KazakusGolemShaper_MageroyalToken,
		CardIds.KazakusGolemShaper_SungrassToken,
		CardIds.KazakusGolemShaper_SwifthistleToken,
		CardIds.KazakusGolemShaper_WildvineToken,
	],
	[CardIds.KoboldTaskmaster]: [CardIds.KoboldTaskmaster_ArmorScrapToken],
	[CardIds.KodoMount]: [CardIds.KodoMount_GuffsKodoToken],
	[CardIds.KolkarPackRunner]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.KreshLordOfTurtling]: [CardIds.KreshLordOfTurtling_TurtleSpikeToken],
	[CardIds.KurtrusDemonRender]: [
		CardIds.KurtrusDemonRender_AshfallensFury,
		CardIds.KurtrusDemonRender_FelbatShriekerToken,
	],
	[CardIds.LightforgedCariel]: [CardIds.LightforgedCariel_BlessingOfQueens, CardIds.TheImmovableObject],
	[CardIds.LilypadLurker]: [CardIds.FrogLegacy],
	[CardIds.LivingSeedRank1]: [
		CardIds.LivingSeedRank1_LivingSeedRank2Token,
		CardIds.LivingSeedRank1_LivingSeedRank3Token,
	],
	[CardIds.LoanShark]: [CardIds.TheCoin1],
	[CardIds.LostInThePark]: [
		CardIds.LostInThePark_DefendTheSquirrelsToken,
		CardIds.LostInThePark_FeralFriendsyToken,
		CardIds.LostInThePark_GuffTheToughToken,
	],
	[CardIds.MagisterDawngrasp]: [CardIds.MagisterDawngrasp_ArcaneBurst],
	[CardIds.MailboxDancer]: [CardIds.TheCoin1],
	[CardIds.Mankrik]: [CardIds.Mankrik_OlgraMankriksWifeToken, CardIds.Mankrik_MankrikConsumedByHatredToken],
	[CardIds.MeetingStone]: ADVENTURER_TOKENS,
	[CardIds.MidaPureLight1]: [CardIds.MidaPureLight_FragmentOfMidaToken],
	[CardIds.MountainBear]: [CardIds.MountainBear_MountainCubToken],
	[CardIds.MorshanWatchPost]: [CardIds.MorshanWatchPost_WatchfulGruntToken],
	[CardIds.NagasPride]: [CardIds.NagasPride_LionfishToken],
	[CardIds.NeeruFireblade1]: [CardIds.NeeruFireblade_BurningBladePortalToken],
	[CardIds.NellieTheGreatThresher]: [CardIds.NellieTheGreatThresher_NelliesPirateShipToken],
	[CardIds.NobleMount]: [CardIds.NobleMount_CarielsWarhorseToken],
	[CardIds.OasisAlly]: [CardIds.WaterElementalLegacy],
	[CardIds.OnyxianWarder]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.RokaraTheValorous]: [
		CardIds.RokaraTheValorous_GrandSlam,
		CardIds.RokaraTheValorous_TheUnstoppableForceToken,
	],
	[CardIds.PartyUp]: ADVENTURER_TOKENS,
	[CardIds.PiranhaPoacher]: PIRANHA_TOKENS,
	[CardIds.PiggybackImp]: [CardIds.PiggybackImp_BackpiggyImpToken],
	[CardIds.PirateAdmiralHooktusk]: [
		CardIds.PirateAdmiralHooktusk_TakeTheirGoldToken,
		CardIds.PirateAdmiralHooktusk_TakeTheirShipToken,
		CardIds.PirateAdmiralHooktusk_TakeTheirSuppliesToken,
	],
	[CardIds.ProtectTheInnocent]: [CardIds.ProtectTheInnocent_StormpikeDefenderToken],
	[CardIds.QueenAzshara2]: [
		CardIds.RingOfTides,
		CardIds.HornOfAncients,
		CardIds.Xalatath,
		CardIds.TidestoneOfGolganneth,
	],
	[CardIds.RaidBossOnyxia1]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.RaidTheDocks]: [
		CardIds.RaidTheDocks_CreateADistractionToken,
		CardIds.RaidTheDocks_SecureTheSuppliesToken,
		CardIds.RaidTheDocks_CapnRokaraToken,
		CardIds.RaidTheDocks_TheJuggernautToken,
	],
	[CardIds.RamCommander]: [CardIds.RamCommander_BattleRamToken],
	[CardIds.RammingMount]: [CardIds.RammingMount_TavishsRamToken],
	[CardIds.RatsOfExtraordinarySize]: [CardIds.RatPack_RatToken],
	[CardIds.Reefwalker]: PIRANHA_TOKENS,
	[CardIds.RemoteControlledGolem]: [CardIds.RemoteControlledGolem_GolemPartsToken],
	[CardIds.RodentNest]: [CardIds.RodentNest_RatToken],
	[CardIds.Rimetongue]: [CardIds.Rimetongue_FrostedElementalToken],
	[CardIds.RiseToTheOccasion]: [
		CardIds.RiseToTheOccasion_AvengeTheFallenToken,
		CardIds.RiseToTheOccasion_PaveTheWayToken,
		CardIds.RiseToTheOccasion_LightbornCarielToken,
		CardIds.LightsJusticeLegacy,
	],
	[CardIds.ScaleOfOnyxia]: [CardIds.OnyxianWarder_OnyxianWhelpToken],
	[CardIds.Scrapsmith]: [CardIds.Scrapsmith_ScrappyGruntToken],
	[CardIds.Schooling]: PIRANHA_TOKENS,
	[CardIds.SchoolTeacher]: [CardIds.SchoolTeacher_NagalingToken],
	[CardIds.SeascoutOperator]: [CardIds.SeascoutOperator_MechafishToken],
	[CardIds.SeedsOfDestruction]: [CardIds.DreadlichTamsin_FelRiftToken, CardIds.DreadlichTamsin_DreadImpToken],
	[CardIds.SeekGuidance]: [
		CardIds.SeekGuidance_DiscoverTheVoidShardToken,
		CardIds.SeekGuidance_IlluminateTheVoidToken,
		CardIds.SeekGuidance_XyrellaTheSanctifiedToken,
	],
	[CardIds.ShadowcrafterScabbs]: [CardIds.ShadowcrafterScabbs_SleightOfHand, CardIds.ShadowcrafterScabbs_ShadowToken],
	[CardIds.SigilOfSummoning]: [CardIds.SigilOfSummoning_WailingDemonToken],
	[CardIds.SindoreiScentfinder]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.SirakessCultist]: [CardIds.SirakessCultist_AbyssalCurseToken],
	[CardIds.Sleetbreaker]: [CardIds.Windchill1],
	[CardIds.SoldiersCaravan]: [CardIds.SilverHandRecruitLegacyToken],
	[CardIds.SorcerersGambit]: [
		CardIds.SorcerersGambit_StallForTimeToken,
		CardIds.SorcerersGambit_ReachThePortalRoomToken,
		CardIds.SorcerersGambit_ArcanistDawngraspToken,
	],
	[CardIds.SowTheSoil]: [CardIds.SowTheSoil_TreantToken],
	[CardIds.SpawnpoolForager]: [CardIds.SpawnpoolForager_DiremuckTinyfinToken],
	[CardIds.SpiritAlpha]: [CardIds.SpiritWolfLegacy],
	[CardIds.SpiritMount]: [CardIds.SpiritMount_BrukansRaptorToken],
	[CardIds.TameBeastRank1]: [
		CardIds.TameBeastRank1_TameBeastRank2Token,
		CardIds.TameBeastRank1_TameBeastRank3Token,
		CardIds.TameBeastRank1_TamedCrabToken,
		CardIds.TameBeastRank1_TamedScorpidToken,
		CardIds.TameBeastRank1_TamedThunderLizardToken,
	],
	[CardIds.TheDemonSeed]: [
		CardIds.TheDemonSeed_CompleteTheRitualToken,
		CardIds.TheDemonSeed_EstablishTheLinkToken,
		CardIds.TheDemonSeed_BlightbornTamsinToken,
	],
	[CardIds.TheLeviathan]: [CardIds.TheLeviathan_TheLeviathansClawToken],
	[CardIds.ThorngrowthSentries]: [CardIds.ThorngrowthSentries_ThornguardTurtleToken],
	[CardIds.VeteranWarmedic]: [CardIds.VeteranWarmedic_BattlefieldMedicToken],
	[CardIds.VibrantSquirrel]: [CardIds.VibrantSquirrel_AcornToken, CardIds.VibrantSquirrel_SatisfiedSquirrelToken],
	[CardIds.VileCall]: [CardIds.VileCall_RavenousVilefiendToken],
	[CardIds.WickedShipment]: [CardIds.ImpGangBoss_ImpToken],
	[CardIds.WickedStabRank1]: [
		CardIds.WickedStabRank1_WickedStabRank2Token,
		CardIds.WickedStabRank1_WickedStabRank3Token,
	],
	[CardIds.WildpawCavern]: [CardIds.BearonGlashear_FrozenStagguardToken],
	[CardIds.WildheartGuff]: [CardIds.WildheartGuff_Nurture],
	[CardIds.WingCommanderMulverick]: [CardIds.WingCommanderMulverick_StrikeWyvernToken],
	[CardIds.WingsOfHateRank1]: [
		CardIds.WingsOfHateRank1_WingsOfHateRank2Token,
		CardIds.WingsOfHateRank1_WingsOfHateRank3Token,
		CardIds.Umberwing_FelwingToken,
	],
	[CardIds.WoundPrey]: [CardIds.KolkarPackRunner_SwiftHyenaToken],
	[CardIds.XhilagOfTheAbyss]: [
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken1,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken2,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken3,
		CardIds.XhilagOfTheAbyss_XhilagsStalkToken4,
	],
	[CardIds.XyrellaTheDevout]: [CardIds.XyrellaTheDevout_HolyTouch, CardIds.XyrellaTheDevout_VoidSpike],
	[CardIds.YseraLegacy]: DREAM_CARDS,
	[CardIds.YseraVanilla]: [
		CardIds.DreamVanilla,
		CardIds.EmeraldDrakeVanilla,
		CardIds.LaughingSisterVanilla,
		CardIds.NightmareVanilla,
		CardIds.YseraAwakensVanilla,
	],
	[CardIds.Zaqul]: [CardIds.SirakessCultist_AbyssalCurseToken],
};
