export enum ScenarioId {
	PRACTICE_MAGE = 252,
	PRACTICE_WARLOCK = 253,
	PRACTICE_HUNTER = 256,
	PRACTICE_ROGUE = 257,
	PRACTICE_PRIEST = 258,
	PRACTICE_WARRIOR = 259,
	PRACTICE_DRUID = 261,
	PRACTICE_PALADIN = 262,
	PRACTICE_SHAMAN = 263,
	PRACTICE_DEMON_HUNTER = 3608,
	PRACTICE_MAGE_EXPERT = 260,
	PRACTICE_WARRIOR_EXPERT = 264,
	PRACTICE_PRIEST_EXPERT = 265,
	PRACTICE_WARLOCK_EXPERT = 266,
	PRACTICE_DRUID_EXPERT = 267,
	PRACTICE_ROGUE_EXPERT = 268,
	PRACTICE_HUNTER_EXPERT = 269,
	PRACTICE_PALADIN_EXPERT = 270,
	PRACTICE_SHAMAN_EXPERT = 271,
	PRACTICE_DEMON_HUNTER_EXPERT = 3609,

	DUNGEON_RUN = 2663,
	MONSTER_HUNT = 2706,
	MONSTER_HUNT_FINAL = 2821,
	RUMBLE_RUN = 2890,

	DALARAN_HEIST_CHAPTER_1 = 3005,
	DALARAN_HEIST_CHAPTER_2 = 3188,
	DALARAN_HEIST_CHAPTER_3 = 3189,
	DALARAN_HEIST_CHAPTER_4 = 3190,
	DALARAN_HEIST_CHAPTER_5 = 3191,
	DALARAN_HEIST_BOB = 3236,
	DALARAN_HEIST_CHAPTER_1_HEROIC = 3328,
	DALARAN_HEIST_CHAPTER_2_HEROIC = 3329,
	DALARAN_HEIST_CHAPTER_3_HEROIC = 3330,
	DALARAN_HEIST_CHAPTER_4_HEROIC = 3331,
	DALARAN_HEIST_CHAPTER_5_HEROIC = 3332,
	DALARAN_HEIST_BOB_HEROIC = 3359,

	TOMBS_OF_TERROR_CHAPTER_1 = 3428,
	TOMBS_OF_TERROR_CHAPTER_2 = 3429,
	TOMBS_OF_TERROR_CHAPTER_3 = 3430,
	TOMBS_OF_TERROR_CHAPTER_4 = 3431,
	TOMBS_OF_TERROR_CHAPTER_5 = 3432,
	TOMBS_OF_TERROR_BOB = 3438,
	TOMBS_OF_TERROR_CHAPTER_1_HEROIC = 3433,
	TOMBS_OF_TERROR_CHAPTER_2_HEROIC = 3434,
	TOMBS_OF_TERROR_CHAPTER_3_HEROIC = 3435,
	TOMBS_OF_TERROR_CHAPTER_4_HEROIC = 3436,
	TOMBS_OF_TERROR_CHAPTER_5_HEROIC = 3437,
	TOMBS_OF_TERROR_BOB_HEROIC = 3439,

	BATTLEGROUNDS = 3539,

	GALAKROND_EXPLORER_CHAP_1_FIGHT_1 = 3469, // Chap 1, Fight 1, Explorer (Finley vs Boom)
	GALAKROND_EXPLORER_CHAP_1_FIGHT_2 = 3470, // Chap 1, Fight 2, Explorer (Khadgar vs Avalanchan)
	GALAKROND_EXPLORER_CHAP_1_FIGHT_3 = 3471, // Chap 1, Fight 3, Explorer (Elise vs Kriziki the Wind)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_1 = 3472, // Chap 2, Fight 1, Explorer (Finley vs Puppetmaster Lazul)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_2 = 3473, // Chap 2, Fight 2, Explorer (vs Cultist Dawnshatter)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_3 = 3475, // Chap 2, Fight 3, Explorer (vs Hagatha the Vengeful)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_1 = 3477, // Chap 3, Fight 1, Explorer (vs Rotwing)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_2 = 3478, // Chap 3, Fight 2, Explorer (vs Dragonslayer Skruk)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_3 = 3479, // Chap 3, Fight 3, Explorer (vs The Slipstream)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_1 = 3480, // Chap 4, Fight 1, Explorer (vs George the Fallen)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_2 = 3481, // Chap 4, Fight 2, Explorer (vs Togwaggle)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_3 = 3483, // Chap 4, Fight 3, Explorer (vs Rafaam and Galakrond)
	GALAKROND_EVIL_CHAP_1_FIGHT_1 = 3484, // Chap 1, Fight 1, EVIL (Kriziki vs Finley)
	GALAKROND_EVIL_CHAP_1_FIGHT_2 = 3488, // Chap 1, Fight 2, EVIL (vs Chenvaala)
	GALAKROND_EVIL_CHAP_1_FIGHT_3 = 3489, // Chap 1, Fight 3, EVIL (Boom vs Reno)
	GALAKROND_EVIL_CHAP_2_FIGHT_1 = 3490, // Chap 2, Fight 1, EVIL (Waxmancer vs Dragoncaster Askaara)
	GALAKROND_EVIL_CHAP_2_FIGHT_2 = 3491, // Chap 2, Fight 2, EVIL (Kronx vs United Sr Explorers)
	GALAKROND_EVIL_CHAP_2_FIGHT_3 = 3493, // Chap 2, Fight 3, EVIL (Hagatha vs Nithogg)
	GALAKROND_EVIL_CHAP_3_FIGHT_1 = 3494, // Chap 3, Fight 1, EVIL (vs Dragonrider Talritha)
	GALAKROND_EVIL_CHAP_3_FIGHT_2 = 3495, // Chap 3, Fight 2, EVIL (vs The Wanderer)
	GALAKROND_EVIL_CHAP_3_FIGHT_3 = 3497, // Chap 3, Fight 3, EVIL (vs The Dragonflights)
	GALAKROND_EVIL_CHAP_4_FIGHT_1 = 3498, // Chap 4, Fight 1, EVIL (vs George and Karl)
	GALAKROND_EVIL_CHAP_4_FIGHT_2 = 3499, // Chap 4, Fight 2, EVIL (vs Reno)
	GALAKROND_EVIL_CHAP_4_FIGHT_3 = 3500, // Chap 4, Fight 3, EVIL (vs Galakrond)
	GALAKROND_EXPLORER_CHAP_1_FIGHT_1_HEROIC = 3556, // Heroic Chap 1, Fight 1, Explorer (vs Boom)
	GALAKROND_EXPLORER_CHAP_1_FIGHT_2_HEROIC = 3583, // Heroic Chap 1, Fight 2, Explorer (vs Avalanchan)
	GALAKROND_EXPLORER_CHAP_1_FIGHT_3_HEROIC = 3584, // Heroic Chap 1, Fight 3, Explorer (vs Kriziki)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_1_HEROIC = 3585, // Heroic Chap 2, Fight 1, Explorer (Finley vs Madam Lazul)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_2_HEROIC = 3586, // Heroic Chap 2, Fight 2, Explorer (vs Cultist Dawnshatter)
	GALAKROND_EXPLORER_CHAP_2_FIGHT_3_HEROIC = 3587, // Heroic Chap 2, Fight 3, Explorer (vs Hagatha the Vengeful)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_1_HEROIC = 3588, // Heroic Chap 3, Fight 1, Explorer (vs Rotwing)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_2_HEROIC = 3589, // Heroic Chap 3, Fight 2, Explorer (vs Dragonslayer Skruk)
	GALAKROND_EXPLORER_CHAP_3_FIGHT_3_HEROIC = 3590, // Heroic Chap 3, Fight 3, Explorer (vs The Slipstream)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_1_HEROIC = 3591, // Heroic Chap 4, Fight 1, Explorer (vs George the Fallen)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_2_HEROIC = 3592, // Heroic Chap 4, Fight 2, Explorer (vs Togwaggle)
	GALAKROND_EXPLORER_CHAP_4_FIGHT_3_HEROIC = 3593, // Heroic Chap 4, Fight 3, Explorer (vs Rafaam and Galakrond)
	GALAKROND_EVIL_CHAP_1_FIGHT_1_HEROIC = 3594, // Heroic Chap 1, Fight 1, EVIL (vs Finley)
	GALAKROND_EVIL_CHAP_1_FIGHT_2_HEROIC = 3595, // Heroic Chap 1, Fight 2, EVIL (vs Chenvaala)
	GALAKROND_EVIL_CHAP_1_FIGHT_3_HEROIC = 3596, // Heroic Chap 1, Fight 3, EVIL (vs Reno)
	GALAKROND_EVIL_CHAP_2_FIGHT_1_HEROIC = 3597, // Heroic Chap 2, Fight 1, EVIL (Waxmancer vs Dragoncaster Askaraa)
	GALAKROND_EVIL_CHAP_2_FIGHT_2_HEROIC = 3598, // Heroic Chap 2, Fight 2, EVIL (Kronx vs United Sr Explorers)
	GALAKROND_EVIL_CHAP_2_FIGHT_3_HEROIC = 3599, // Heroic Chap 2, Fight 3, EVIL (Hagatha vs Nitthog)
	GALAKROND_EVIL_CHAP_3_FIGHT_1_HEROIC = 3600, // Heroic Chap 3, Fight 1, EVIL (vs Dragonrider Talritha)
	GALAKROND_EVIL_CHAP_3_FIGHT_2_HEROIC = 3601, // Heroic Chap 3, Fight 2, EVIL (vs The Wanderer)
	GALAKROND_EVIL_CHAP_3_FIGHT_3_HEROIC = 3602, // Heroic Chap 3, Fight 3, EVIL (vs The Dragonflights)
	GALAKROND_EVIL_CHAP_4_FIGHT_1_HEROIC = 3603, // Heroic Chap 4, Fight 1, EVIL (vs George and Karl)
	GALAKROND_EVIL_CHAP_4_FIGHT_2_HEROIC = 3604, // Heroic Chap 4, Fight 2, EVIL (vs Reno)
	GALAKROND_EVIL_CHAP_4_FIGHT_3_HEROIC = 3605, // Heroic Chap 4, Fight 3, EVIL (vs Galakrond)
	TRIAL_BY_FELFIRE_CHAPTER_1_FIGHT_1 = 3557, // Inquisitor Dakrelm
	TRIAL_BY_FELFIRE_CHAPTER_1_FIGHT_2 = 3558, // Xur'goth
	TRIAL_BY_FELFIRE_CHAPTER_1_FIGHT_3 = 3559, // Zixor, Apex Predator
	TRIAL_BY_FELFIRE_CHAPTER_1_FIGHT_4 = 3560, // Baltharak
	TRIAL_BY_FELFIRE_CHAPTER_2_FIGHT_1 = 3561, // Kanrethad Prime
	TRIAL_BY_FELFIRE_CHAPTER_2_FIGHT_2 = 3562, // Burgrak Cruelchain
	TRIAL_BY_FELFIRE_CHAPTER_2_FIGHT_3 = 3563, // Felstorm Run
	TRIAL_BY_FELFIRE_CHAPTER_2_FIGHT_4 = 3564, // Mother Shahraz
	TRIAL_BY_FELFIRE_CHAPTER_3_FIGHT_1 = 3565, // Shalja, Outcast
	TRIAL_BY_FELFIRE_CHAPTER_3_FIGHT_2 = 3566, // Karnuk, Outcast
	TRIAL_BY_FELFIRE_CHAPTER_3_FIGHT_3 = 3567, // Jek'haz
	TRIAL_BY_FELFIRE_CHAPTER_3_FIGHT_4 = 3568, // Magtheridon Prime
	TRIAL_BY_FELFIRE_CHAPTER_4_FIGHT_1 = 3569, // Gok'amok
	TRIAL_BY_FELFIRE_CHAPTER_4_FIGHT_2 = 3570, // Flikk (transforms into Rusted Fel Reaver)
	TRIAL_BY_FELFIRE_CHAPTER_4_FIGHT_3 = 3571, // Baduu Prime
	TRIAL_BY_FELFIRE_CHAPTER_4_FIGHT_4 = 3572, // Mecha-Jaraxxus
	TRIAL_BY_FELFIRE_CHAPTER_5 = 3573, // Illidan
}

export const GALAKROND_EXPLORER = [
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_1,
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_2,
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_3,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_1,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_2,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_3,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_1,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_2,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_3,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_1,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_2,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_3,
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_1_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_2_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_3_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EXPLORER_CHAP_4_FIGHT_3_HEROIC,
];

export const GALAKROND_EVIL = [
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_1,
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_2,
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_3,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_1,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_2,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_3,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_1,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_2,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_3,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_1,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_2,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_3,
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_1_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_2_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_3_FIGHT_3_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_1_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_2_HEROIC,
	ScenarioId.GALAKROND_EVIL_CHAP_4_FIGHT_3_HEROIC,
];

export const GALAKROND_ALL = [...GALAKROND_EXPLORER, ...GALAKROND_EVIL];
